---
title: "ZINB_Vary N Results"
author: "Zahra"
date: "2023-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Scenario6: size(10,100), function: disp_para


```{r Sc6,echo=FALSE,eval=TRUE}
rm(list = ls())

P_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/P_sim1_n60.csv")
Phi_sim1_n60 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/Phi_sim1_n60.csv")
overdisp_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/overdisp_sim1_n60.csv")
size_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/size_sim1_n60.csv")
MU1_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU1_sim1_n60.csv")
MU2_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU2_sim1_n60.csv")
V_M_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/v_M_sim1_n60.csv")
elapsed_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/elapsed_sim1_n60.csv")
######################################################################################################################################
P_sim1_n60<- P_sim1_n60[,-1]
Phi_sim1_n60<- Phi_sim1_n60[,-1]
overdisp_sim1_n60<- overdisp_sim1_n60[,-1]
size_sim1_n60<- size_sim1_n60[,-1]
MU1_sim1_n60<- MU1_sim1_n60[,-1]
MU2_sim1_n60<- MU2_sim1_n60[,-1]
V_M_sim1_n60<- V_M_sim1_n60[,-1]
elapsed_sim1_n60<- elapsed_sim1_n60[,-1]

#######################################################################################################################################
P_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/P_sim2_n120.csv")
Phi_sim2_n120 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/Phi_sim2_n120.csv")
overdisp_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/overdisp_sim2_n120.csv")
size_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/size_sim2_n120.csv")
MU1_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU1_sim2_n120.csv")
MU2_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU2_sim2_n120.csv")
V_M_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/v_M_sim2_n120.csv")
elapsed_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/elapsed_sim2_n120.csv")
######################################################################################################################################
P_sim2_n120<- P_sim2_n120[,-1]
Phi_sim2_n120<- Phi_sim2_n120[,-1]
overdisp_sim2_n120<- overdisp_sim2_n120[,-1]
size_sim2_n120<- size_sim2_n120[,-1]
MU1_sim2_n120<- MU1_sim2_n120[,-1]
MU2_sim2_n120<- MU2_sim2_n120[,-1]
V_M_sim2_n120<- V_M_sim2_n120[,-1]
elapsed_sim2_n120<- elapsed_sim2_n120[,-1]

#######################################################################################################################################
P_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/P_sim3_n300.csv")
Phi_sim3_n300 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/Phi_sim3_n300.csv")
overdisp_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/overdisp_sim3_n300.csv")
size_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/size_sim3_n300.csv")
MU1_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU1_sim3_n300.csv")
MU2_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU2_sim3_n300.csv")
V_M_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/v_M_sim3_n300.csv")
elapsed_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/elapsed_sim3_n300.csv")
######################################################################################################################################
P_sim3_n300<- P_sim3_n300[,-1]
Phi_sim3_n300<- Phi_sim3_n300[,-1]
overdisp_sim3_n300<- overdisp_sim3_n300[,-1]
size_sim3_n300<- size_sim3_n300[,-1]
MU1_sim3_n300<- MU1_sim3_n300[,-1]
MU2_sim3_n300<- MU2_sim3_n300[,-1]
V_M_sim3_n300<- V_M_sim3_n300[,-1]
elapsed_sim3_n300<- elapsed_sim3_n300[,-1]

#######################################################################################################################################
#######################################################################################################################################

P_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/P_sim4_n600.csv")
Phi_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/Phi_sim4_n600.csv")
overdisp_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/overdisp_sim4_n600.csv")
size_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/size_sim4_n600.csv")
MU1_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU1_sim4_n600.csv")
MU2_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU2_sim4_n600.csv")
V_M_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/v_M_sim4_n600.csv")
elapsed_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/elapsed_sim4_n600.csv")

P_sim4_n600<- P_sim4_n600[,-1]
Phi_sim4_n600<- Phi_sim4_n600[,-1]
overdisp_sim4_n600<- overdisp_sim4_n600[,-1]
size_sim4_n600<- size_sim4_n600[,-1]
MU1_sim4_n600<- MU1_sim4_n600[,-1]
MU2_sim4_n600<- MU2_sim4_n600[,-1]
V_M_sim4_n600<- V_M_sim4_n600[,-1]
elapsed_sim4_n600<- elapsed_sim4_n600[,-1]

#############################################################################################################################



P_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/P_sim5_n1200.csv")
Phi_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/Phi_sim5_n1200.csv")
overdisp_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/overdisp_sim5_n1200.csv")
size_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/size_sim5_n1200.csv")
MU1_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU1_sim5_n1200.csv")
MU2_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/MU2_sim5_n1200.csv")
V_M_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/v_M_sim5_n1200.csv")
elapsed_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario6/elapsed_sim5_n1200.csv")

P_sim5_n1200<- P_sim5_n1200[,-1]
Phi_sim5_n1200<- Phi_sim5_n1200[,-1]
overdisp_sim5_n1200<- overdisp_sim5_n1200[,-1]
size_sim5_n1200<- size_sim5_n1200[,-1]
MU1_sim5_n1200<- MU1_sim5_n1200[,-1]
MU2_sim5_n1200<- MU2_sim5_n1200[,-1]
V_M_sim5_n1200<- V_M_sim5_n1200[,-1]
elapsed_sim5_n1200<- elapsed_sim5_n1200[,-1]
###########################################################################################################################
#size_sim1_n60
#size_sim2_n120
#size_sim3_n300
#size_sim5_n1200
#############################################################################################################################
par(mfrow=c(2,2))
boxplot(size_sim1_n60[,1],size_sim2_n120[,1],size_sim3_n300[,1],size_sim4_n600[,1],size_sim5_n1200[,1],main=expression(nu[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=10)

boxplot(size_sim1_n60[,2],size_sim2_n120[,2],size_sim3_n300[,2],size_sim4_n600[,2],size_sim5_n1200[,2],main=expression(nu[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=100)

boxplot(size_sim1_n60[,1],size_sim2_n120[,1],size_sim3_n300[,1],size_sim4_n600[,1],size_sim5_n1200[,1],main=expression(nu[1]),outline =FALSE,xlab="N_rm_oultiler",names=c(60,120,300,600,1200))
abline(h=10)

boxplot(size_sim1_n60[,2],size_sim2_n120[,2],size_sim3_n300[,2],size_sim4_n600[,2],size_sim5_n1200[,2],main=expression(nu[2]),outline = FALSE,xlab="N_rm_outlier",names=c(60,120,300,600,1200))
abline(h=100)

#################################################################################################################################
par(mfrow=c(2,2))
boxplot(P_sim1_n60[,1],P_sim2_n120[,1],P_sim3_n300[,1],P_sim4_n600[,1],P_sim5_n1200[,1],main=expression(pi[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.5)

boxplot(P_sim1_n60[,2],P_sim2_n120[,2],P_sim3_n300[,2],P_sim4_n600[,2],P_sim5_n1200[,2],main=expression(pi[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.5)

############################################################################################################################
#par(mfrow=c(2,2))
boxplot(Phi_sim1_n60[,1],Phi_sim2_n120[,1],Phi_sim3_n300[,1],Phi_sim4_n600[,1],Phi_sim5_n1200[,1],main=expression(phi[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.1)

boxplot(Phi_sim1_n60[,2],Phi_sim2_n120[,2],Phi_sim3_n300[,2],Phi_sim4_n600[,2],Phi_sim5_n1200[,2],main=expression(phi[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.1)

############################################################################################################################
#par(mfrow=c(1,2))
boxplot(V_M_sim1_n60,V_M_sim2_n120,V_M_sim3_n300,V_M_sim4_n600,V_M_sim5_n1200,main="V-Measures",xlab="N",names=c(60,120,300,600,1200))
abline(h=1)



#################################################################################################################################
MSE_MU1_est<- c(mean(MU1_sim1_n60),mean(MU1_sim2_n120),mean(MU1_sim3_n300),mean(MU1_sim4_n600),mean(MU1_sim5_n1200))
paste("MSE_MU_hat1:",MSE_MU1_est)
print(MSE_MU1_est)
MSE_MU2_est<- c(mean(MU2_sim1_n60),mean(MU2_sim2_n120),mean(MU2_sim3_n300),mean(MU2_sim4_n600),mean(MU2_sim5_n1200))
paste("MSE_MU_hat2:",MSE_MU2_est)
print(MSE_MU2_est)
#################################################################################################################
MSE_Size1_60<- mean((size_sim1_n60[,1]-10)^2)
MSE_Size1_120<- mean((size_sim2_n120[,1]-10)^2)
MSE_Size1_300<- mean((size_sim3_n300[,1]-10)^2)
MSE_Size1_600<- mean((size_sim4_n600[,1]-10)^2)
MSE_Size1_1200<- mean((size_sim5_n1200[,1]-10)^2)
MSE_1<- c(MSE_Size1_60,MSE_Size1_120,MSE_Size1_300,MSE_Size1_600,MSE_Size1_1200)
###For size
print(MSE_1)

MSE_Size2_60<- mean((size_sim1_n60[,2]-100)^2)
MSE_Size2_120<- mean((size_sim2_n120[,2]-100)^2)
MSE_Size2_300<- mean((size_sim3_n300[,2]-100)^2)
MSE_Size2_600<- mean((size_sim4_n600[,2]-100)^2)
MSE_Size2_1200<- mean((size_sim5_n1200[,2]-100)^2)
MSE_2<- c(MSE_Size2_60,MSE_Size2_120,MSE_Size2_300,MSE_Size2_600,MSE_Size2_1200)
print(MSE_2)

#MSE_S<- rbind(MSE_1,MSE_2)
#colnames(MSE_S)<- c(60,120,300,600,1200)
#MSE_S

##################################################################################################################
# 
# MAD_Size1_60<- median(abs(size_sim1_n60[,1]-5))
# MAD_Size1_120<- median(abs(size_sim2_n120[,1]-5))
# MAD_Size1_300<- median(abs(size_sim3_n300[,1]-5))
# MAD_Size1_600<- median(abs(size_sim4_n600[,1]-5))
# MAD_Size1_1200<- median(abs(size_sim4_n1200[,1]-5))
# MAD_1<- c(MAD_Size1_60,MAD_Size1_120,MAD_Size1_300,MAD_Size1_600,MAD_Size1_1200)
# MAD_1
# 
# MAD_Size2_60<- median(abs(size_sim1_n60[,2]-5))
# MAD_Size2_120<- median(abs(size_sim2_n120[,2]-5))
# MAD_Size2_300<- median(abs(size_sim3_n300[,2]-5))
# MAD_Size2_600<- median(abs(size_sim4_n600[,2]-5))
# MAD_Size2_1200<- median(abs(size_sim5_n1200[,2]-5))
# MAD_2<- c(MAD_Size2_60,MAD_Size2_120,MAD_Size2_300,MAD_Size2_600,MAD_Size2_1200)
# MAD_2
# 
# MAD_S<- rbind(MAD_1,MAD_2)
# colnames(MAD_S)<- c(60,120,300,600,1200)
# MAD_S
# 





```


## Scenario7: size(5,20), function: disp_para


```{r Sc7,echo=FALSE,eval=TRUE}
rm(list = ls())

P_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/P_sim1_n60.csv")
Phi_sim1_n60 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/Phi_sim1_n60.csv")
overdisp_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/overdisp_sim1_n60.csv")
size_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/size_sim1_n60.csv")
MU1_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU1_sim1_n60.csv")
MU2_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU2_sim1_n60.csv")
V_M_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/v_M_sim1_n60.csv")
elapsed_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/elapsed_sim1_n60.csv")
######################################################################################################################################
P_sim1_n60<- P_sim1_n60[,-1]
Phi_sim1_n60<- Phi_sim1_n60[,-1]
overdisp_sim1_n60<- overdisp_sim1_n60[,-1]
size_sim1_n60<- size_sim1_n60[,-1]
MU1_sim1_n60<- MU1_sim1_n60[,-1]
MU2_sim1_n60<- MU2_sim1_n60[,-1]
V_M_sim1_n60<- V_M_sim1_n60[,-1]
elapsed_sim1_n60<- elapsed_sim1_n60[,-1]

#######################################################################################################################################
P_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/P_sim2_n120.csv")
Phi_sim2_n120 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/Phi_sim2_n120.csv")
overdisp_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/overdisp_sim2_n120.csv")
size_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/size_sim2_n120.csv")
MU1_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU1_sim2_n120.csv")
MU2_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU2_sim2_n120.csv")
V_M_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/v_M_sim2_n120.csv")
elapsed_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/elapsed_sim2_n120.csv")
######################################################################################################################################
P_sim2_n120<- P_sim2_n120[,-1]
Phi_sim2_n120<- Phi_sim2_n120[,-1]
overdisp_sim2_n120<- overdisp_sim2_n120[,-1]
size_sim2_n120<- size_sim2_n120[,-1]
MU1_sim2_n120<- MU1_sim2_n120[,-1]
MU2_sim2_n120<- MU2_sim2_n120[,-1]
V_M_sim2_n120<- V_M_sim2_n120[,-1]
elapsed_sim2_n120<- elapsed_sim2_n120[,-1]

#######################################################################################################################################
P_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/P_sim3_n300.csv")
Phi_sim3_n300 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/Phi_sim3_n300.csv")
overdisp_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/overdisp_sim3_n300.csv")
size_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/size_sim3_n300.csv")
MU1_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU1_sim3_n300.csv")
MU2_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU2_sim3_n300.csv")
V_M_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/v_M_sim3_n300.csv")
elapsed_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/elapsed_sim3_n300.csv")
######################################################################################################################################
P_sim3_n300<- P_sim3_n300[,-1]
Phi_sim3_n300<- Phi_sim3_n300[,-1]
overdisp_sim3_n300<- overdisp_sim3_n300[,-1]
size_sim3_n300<- size_sim3_n300[,-1]
MU1_sim3_n300<- MU1_sim3_n300[,-1]
MU2_sim3_n300<- MU2_sim3_n300[,-1]
V_M_sim3_n300<- V_M_sim3_n300[,-1]
elapsed_sim3_n300<- elapsed_sim3_n300[,-1]

#######################################################################################################################################
#######################################################################################################################################

P_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/P_sim4_n600.csv")
Phi_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/Phi_sim4_n600.csv")
overdisp_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/overdisp_sim4_n600.csv")
size_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/size_sim4_n600.csv")
MU1_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU1_sim4_n600.csv")
MU2_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU2_sim4_n600.csv")
V_M_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/v_M_sim4_n600.csv")
elapsed_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/elapsed_sim4_n600.csv")

P_sim4_n600<- P_sim4_n600[,-1]
Phi_sim4_n600<- Phi_sim4_n600[,-1]
overdisp_sim4_n600<- overdisp_sim4_n600[,-1]
size_sim4_n600<- size_sim4_n600[,-1]
MU1_sim4_n600<- MU1_sim4_n600[,-1]
MU2_sim4_n600<- MU2_sim4_n600[,-1]
V_M_sim4_n600<- V_M_sim4_n600[,-1]
elapsed_sim4_n600<- elapsed_sim4_n600[,-1]

#############################################################################################################################



P_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/P_sim5_n1200.csv")
Phi_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/Phi_sim5_n1200.csv")
overdisp_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/overdisp_sim5_n1200.csv")
size_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/size_sim5_n1200.csv")
MU1_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU1_sim5_n1200.csv")
MU2_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/MU2_sim5_n1200.csv")
V_M_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/v_M_sim5_n1200.csv")
elapsed_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario7/elapsed_sim5_n1200.csv")

P_sim5_n1200<- P_sim5_n1200[,-1]
Phi_sim5_n1200<- Phi_sim5_n1200[,-1]
overdisp_sim5_n1200<- overdisp_sim5_n1200[,-1]
size_sim5_n1200<- size_sim5_n1200[,-1]
MU1_sim5_n1200<- MU1_sim5_n1200[,-1]
MU2_sim5_n1200<- MU2_sim5_n1200[,-1]
V_M_sim5_n1200<- V_M_sim5_n1200[,-1]
elapsed_sim5_n1200<- elapsed_sim5_n1200[,-1]
###########################################################################################################################
#size_sim1_n60
#size_sim2_n120
#size_sim3_n300
#size_sim5_n1200
#############################################################################################################################
par(mfrow=c(2,2))
boxplot(size_sim1_n60[,1],size_sim2_n120[,1],size_sim3_n300[,1],size_sim4_n600[,1],size_sim5_n1200[,1],main=expression(nu[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=5)

boxplot(size_sim1_n60[,2],size_sim2_n120[,2],size_sim3_n300[,2],size_sim4_n600[,2],size_sim5_n1200[,2],main=expression(nu[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=20)

boxplot(size_sim1_n60[,1],size_sim2_n120[,1],size_sim3_n300[,1],size_sim4_n600[,1],size_sim5_n1200[,1],main=expression(nu[1]),outline =FALSE,xlab="N_rm_oultiler",names=c(60,120,300,600,1200))
abline(h=5)

boxplot(size_sim1_n60[,2],size_sim2_n120[,2],size_sim3_n300[,2],size_sim4_n600[,2],size_sim5_n1200[,2],main=expression(nu[2]),outline = FALSE,xlab="N_rm_outlier",names=c(60,120,300,600,1200))
abline(h=20)

#################################################################################################################################
par(mfrow=c(2,2))
boxplot(P_sim1_n60[,1],P_sim2_n120[,1],P_sim3_n300[,1],P_sim4_n600[,1],P_sim5_n1200[,1],main=expression(pi[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.5)

boxplot(P_sim1_n60[,2],P_sim2_n120[,2],P_sim3_n300[,2],P_sim4_n600[,2],P_sim5_n1200[,2],main=expression(pi[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.5)

############################################################################################################################
#par(mfrow=c(2,2))
boxplot(Phi_sim1_n60[,1],Phi_sim2_n120[,1],Phi_sim3_n300[,1],Phi_sim4_n600[,1],Phi_sim5_n1200[,1],main=expression(phi[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.1)

boxplot(Phi_sim1_n60[,2],Phi_sim2_n120[,2],Phi_sim3_n300[,2],Phi_sim4_n600[,2],Phi_sim5_n1200[,2],main=expression(phi[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.1)

############################################################################################################################
#par(mfrow=c(1,2))
boxplot(V_M_sim1_n60,V_M_sim2_n120,V_M_sim3_n300,V_M_sim4_n600,V_M_sim5_n1200,main="V-Measures",xlab="N",names=c(60,120,300,600,1200))
abline(h=1)



#################################################################################################################################
MSE_MU1_est<- c(mean(MU1_sim1_n60),mean(MU1_sim2_n120),mean(MU1_sim3_n300),mean(MU1_sim4_n600),mean(MU1_sim5_n1200))
paste("MSE_MU_hat1:",MSE_MU1_est)
print(MSE_MU1_est)
MSE_MU2_est<- c(mean(MU2_sim1_n60),mean(MU2_sim2_n120),mean(MU2_sim3_n300),mean(MU2_sim4_n600),mean(MU2_sim5_n1200))
paste("MSE_MU_hat2:",MSE_MU2_est)
print(MSE_MU2_est)
#################################################################################################################
MSE_Size1_60<- mean((size_sim1_n60[,1]-5)^2)
MSE_Size1_120<- mean((size_sim2_n120[,1]-5)^2)
MSE_Size1_300<- mean((size_sim3_n300[,1]-5)^2)
MSE_Size1_600<- mean((size_sim4_n600[,1]-5)^2)
MSE_Size1_1200<- mean((size_sim5_n1200[,1]-5)^2)
MSE_1<- c(MSE_Size1_60,MSE_Size1_120,MSE_Size1_300,MSE_Size1_600,MSE_Size1_1200)
###For size
print(MSE_1)

MSE_Size2_60<- mean((size_sim1_n60[,2]-20)^2)
MSE_Size2_120<- mean((size_sim2_n120[,2]-20)^2)
MSE_Size2_300<- mean((size_sim3_n300[,2]-20)^2)
MSE_Size2_600<- mean((size_sim4_n600[,2]-20)^2)
MSE_Size2_1200<- mean((size_sim5_n1200[,2]-20)^2)
MSE_2<- c(MSE_Size2_60,MSE_Size2_120,MSE_Size2_300,MSE_Size2_600,MSE_Size2_1200)
print(MSE_2)

#MSE_S<- rbind(MSE_1,MSE_2)
#colnames(MSE_S)<- c(60,120,300,600,1200)
#MSE_S

##################################################################################################################
# 
# MAD_Size1_60<- median(abs(size_sim1_n60[,1]-5))
# MAD_Size1_120<- median(abs(size_sim2_n120[,1]-5))
# MAD_Size1_300<- median(abs(size_sim3_n300[,1]-5))
# MAD_Size1_600<- median(abs(size_sim4_n600[,1]-5))
# MAD_Size1_1200<- median(abs(size_sim4_n1200[,1]-5))
# MAD_1<- c(MAD_Size1_60,MAD_Size1_120,MAD_Size1_300,MAD_Size1_600,MAD_Size1_1200)
# MAD_1
# 
# MAD_Size2_60<- median(abs(size_sim1_n60[,2]-5))
# MAD_Size2_120<- median(abs(size_sim2_n120[,2]-5))
# MAD_Size2_300<- median(abs(size_sim3_n300[,2]-5))
# MAD_Size2_600<- median(abs(size_sim4_n600[,2]-5))
# MAD_Size2_1200<- median(abs(size_sim5_n1200[,2]-5))
# MAD_2<- c(MAD_Size2_60,MAD_Size2_120,MAD_Size2_300,MAD_Size2_600,MAD_Size2_1200)
# MAD_2
# 
# MAD_S<- rbind(MAD_1,MAD_2)
# colnames(MAD_S)<- c(60,120,300,600,1200)
# MAD_S
# 


```


## Scenario8: size(10,100), function: glm.nb


```{r Sc8,echo=FALSE,eval=TRUE}
rm(list = ls())

P_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim1_n60.csv")
Phi_sim1_n60 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/Phi_sim1_n60.csv")
overdisp_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim1_n60.csv")
size_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim1_n60.csv")
MU1_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim1_n60.csv")
MU2_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim1_n60.csv")
V_M_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim1_n60.csv")
elapsed_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim1_n60.csv")
######################################################################################################################################
P_sim1_n60<- P_sim1_n60[,-1]
Phi_sim1_n60<- Phi_sim1_n60[,-1]
overdisp_sim1_n60<- overdisp_sim1_n60[,-1]
size_sim1_n60<- size_sim1_n60[,-1]
MU1_sim1_n60<- MU1_sim1_n60[,-1]
MU2_sim1_n60<- MU2_sim1_n60[,-1]
V_M_sim1_n60<- V_M_sim1_n60[,-1]
elapsed_sim1_n60<- elapsed_sim1_n60[,-1]

#######################################################################################################################################
P_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim2_n120.csv")
Phi_sim2_n120 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/Phi_sim2_n120.csv")
overdisp_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim2_n120.csv")
size_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim2_n120.csv")
MU1_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim2_n120.csv")
MU2_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim2_n120.csv")
V_M_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim2_n120.csv")
elapsed_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim2_n120.csv")
######################################################################################################################################
P_sim2_n120<- P_sim2_n120[,-1]
Phi_sim2_n120<- Phi_sim2_n120[,-1]
overdisp_sim2_n120<- overdisp_sim2_n120[,-1]
size_sim2_n120<- size_sim2_n120[,-1]
MU1_sim2_n120<- MU1_sim2_n120[,-1]
MU2_sim2_n120<- MU2_sim2_n120[,-1]
V_M_sim2_n120<- V_M_sim2_n120[,-1]
elapsed_sim2_n120<- elapsed_sim2_n120[,-1]

#######################################################################################################################################
P_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim3_n300.csv")
Phi_sim3_n300 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/Phi_sim3_n300.csv")
overdisp_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim3_n300.csv")
size_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim3_n300.csv")
MU1_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim3_n300.csv")
MU2_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim3_n300.csv")
V_M_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim3_n300.csv")
elapsed_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim3_n300.csv")
######################################################################################################################################
P_sim3_n300<- P_sim3_n300[,-1]
Phi_sim3_n300<- Phi_sim3_n300[,-1]
overdisp_sim3_n300<- overdisp_sim3_n300[,-1]
size_sim3_n300<- size_sim3_n300[,-1]
MU1_sim3_n300<- MU1_sim3_n300[,-1]
MU2_sim3_n300<- MU2_sim3_n300[,-1]
V_M_sim3_n300<- V_M_sim3_n300[,-1]
elapsed_sim3_n300<- elapsed_sim3_n300[,-1]

#######################################################################################################################################
#######################################################################################################################################

P_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim4_n600.csv")
Phi_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/Phi_sim4_n600.csv")
overdisp_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim4_n600.csv")
size_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim4_n600.csv")
MU1_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim4_n600.csv")
MU2_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim4_n600.csv")
V_M_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim4_n600.csv")
elapsed_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim4_n600.csv")

P_sim4_n600<- P_sim4_n600[,-1]
Phi_sim4_n600<- Phi_sim4_n600[,-1]
overdisp_sim4_n600<- overdisp_sim4_n600[,-1]
size_sim4_n600<- size_sim4_n600[,-1]
MU1_sim4_n600<- MU1_sim4_n600[,-1]
MU2_sim4_n600<- MU2_sim4_n600[,-1]
V_M_sim4_n600<- V_M_sim4_n600[,-1]
elapsed_sim4_n600<- elapsed_sim4_n600[,-1]

#############################################################################################################################



P_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim5_n1200.csv")
Phi_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/Phi_sim5_n1200.csv")
overdisp_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim5_n1200.csv")
size_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim5_n1200.csv")
MU1_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim5_n1200.csv")
MU2_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim5_n1200.csv")
V_M_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim5_n1200.csv")
elapsed_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim5_n1200.csv")

P_sim5_n1200<- P_sim5_n1200[,-1]
Phi_sim5_n1200<- Phi_sim5_n1200[,-1]
overdisp_sim5_n1200<- overdisp_sim5_n1200[,-1]
size_sim5_n1200<- size_sim5_n1200[,-1]
MU1_sim5_n1200<- MU1_sim5_n1200[,-1]
MU2_sim5_n1200<- MU2_sim5_n1200[,-1]
V_M_sim5_n1200<- V_M_sim5_n1200[,-1]
elapsed_sim5_n1200<- elapsed_sim5_n1200[,-1]
###########################################################################################################################
#size_sim1_n60
#size_sim2_n120
#size_sim3_n300
#size_sim5_n1200
#############################################################################################################################
par(mfrow=c(2,2))
boxplot(size_sim1_n60[,1],size_sim2_n120[,1],size_sim3_n300[,1],size_sim4_n600[,1],size_sim5_n1200[,1],main=expression(nu[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=10)

boxplot(size_sim1_n60[,2],size_sim2_n120[,2],size_sim3_n300[,2],size_sim4_n600[,2],size_sim5_n1200[,2],main=expression(nu[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=100)

boxplot(size_sim1_n60[,1],size_sim2_n120[,1],size_sim3_n300[,1],size_sim4_n600[,1],size_sim5_n1200[,1],main=expression(nu[1]),outline =FALSE,xlab="N_rm_oultiler",names=c(60,120,300,600,1200))
abline(h=10)

boxplot(size_sim1_n60[,2],size_sim2_n120[,2],size_sim3_n300[,2],size_sim4_n600[,2],size_sim5_n1200[,2],main=expression(nu[2]),outline = FALSE,xlab="N_rm_outlier",names=c(60,120,300,600,1200))
abline(h=100)

#################################################################################################################################
par(mfrow=c(2,2))
boxplot(P_sim1_n60[,1],P_sim2_n120[,1],P_sim3_n300[,1],P_sim4_n600[,1],P_sim5_n1200[,1],main=expression(pi[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.5)

boxplot(P_sim1_n60[,2],P_sim2_n120[,2],P_sim3_n300[,2],P_sim4_n600[,2],P_sim5_n1200[,2],main=expression(pi[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.5)

############################################################################################################################
#par(mfrow=c(2,2))
boxplot(Phi_sim1_n60[,1],Phi_sim2_n120[,1],Phi_sim3_n300[,1],Phi_sim4_n600[,1],Phi_sim5_n1200[,1],main=expression(phi[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.1)

boxplot(Phi_sim1_n60[,2],Phi_sim2_n120[,2],Phi_sim3_n300[,2],Phi_sim4_n600[,2],Phi_sim5_n1200[,2],main=expression(phi[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.1)

############################################################################################################################
#par(mfrow=c(1,2))
boxplot(V_M_sim1_n60,V_M_sim2_n120,V_M_sim3_n300,V_M_sim4_n600,V_M_sim5_n1200,main="V-Measures",xlab="N",names=c(60,120,300,600,1200))
abline(h=1)



#################################################################################################################################
MSE_MU1_est<- c(mean(MU1_sim1_n60),mean(MU1_sim2_n120),mean(MU1_sim3_n300),mean(MU1_sim4_n600),mean(MU1_sim5_n1200))
paste("MSE_MU_hat1:",MSE_MU1_est)
print(MSE_MU1_est)
MSE_MU2_est<- c(mean(MU2_sim1_n60),mean(MU2_sim2_n120),mean(MU2_sim3_n300),mean(MU2_sim4_n600),mean(MU2_sim5_n1200))
paste("MSE_MU_hat2:",MSE_MU2_est)
print(MSE_MU2_est)
#################################################################################################################
MSE_Size1_60<- mean((size_sim1_n60[,1]-10)^2)
MSE_Size1_120<- mean((size_sim2_n120[,1]-10)^2)
MSE_Size1_300<- mean((size_sim3_n300[,1]-10)^2)
MSE_Size1_600<- mean((size_sim4_n600[,1]-10)^2)
MSE_Size1_1200<- mean((size_sim5_n1200[,1]-10)^2)
MSE_1<- c(MSE_Size1_60,MSE_Size1_120,MSE_Size1_300,MSE_Size1_600,MSE_Size1_1200)
###For size
print(MSE_1)

MSE_Size2_60<- mean((size_sim1_n60[,2]-100)^2)
MSE_Size2_120<- mean((size_sim2_n120[,2]-100)^2)
MSE_Size2_300<- mean((size_sim3_n300[,2]-100)^2)
MSE_Size2_600<- mean((size_sim4_n600[,2]-100)^2)
MSE_Size2_1200<- mean((size_sim5_n1200[,2]-100)^2)
MSE_2<- c(MSE_Size2_60,MSE_Size2_120,MSE_Size2_300,MSE_Size2_600,MSE_Size2_1200)
print(MSE_2)

#MSE_S<- rbind(MSE_1,MSE_2)
#colnames(MSE_S)<- c(60,120,300,600,1200)
#MSE_S

##################################################################################################################
# 
# MAD_Size1_60<- median(abs(size_sim1_n60[,1]-5))
# MAD_Size1_120<- median(abs(size_sim2_n120[,1]-5))
# MAD_Size1_300<- median(abs(size_sim3_n300[,1]-5))
# MAD_Size1_600<- median(abs(size_sim4_n600[,1]-5))
# MAD_Size1_1200<- median(abs(size_sim4_n1200[,1]-5))
# MAD_1<- c(MAD_Size1_60,MAD_Size1_120,MAD_Size1_300,MAD_Size1_600,MAD_Size1_1200)
# MAD_1
# 
# MAD_Size2_60<- median(abs(size_sim1_n60[,2]-5))
# MAD_Size2_120<- median(abs(size_sim2_n120[,2]-5))
# MAD_Size2_300<- median(abs(size_sim3_n300[,2]-5))
# MAD_Size2_600<- median(abs(size_sim4_n600[,2]-5))
# MAD_Size2_1200<- median(abs(size_sim5_n1200[,2]-5))
# MAD_2<- c(MAD_Size2_60,MAD_Size2_120,MAD_Size2_300,MAD_Size2_600,MAD_Size2_1200)
# MAD_2
# 
# MAD_S<- rbind(MAD_1,MAD_2)
# colnames(MAD_S)<- c(60,120,300,600,1200)
# MAD_S
# 



```


## Scenario9: size(5,20), function: glm.nb


```{r Sc9,echo=FALSE,eval=TRUE}
rm(list = ls())

P_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/P_sim1_n60.csv")
Phi_sim1_n60 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/Phi_sim1_n60.csv")
overdisp_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/overdisp_sim1_n60.csv")
size_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/size_sim1_n60.csv")
MU1_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU1_sim1_n60.csv")
MU2_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU2_sim1_n60.csv")
V_M_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/v_M_sim1_n60.csv")
elapsed_sim1_n60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/elapsed_sim1_n60.csv")
######################################################################################################################################
P_sim1_n60<- P_sim1_n60[,-1]
Phi_sim1_n60<- Phi_sim1_n60[,-1]
overdisp_sim1_n60<- overdisp_sim1_n60[,-1]
size_sim1_n60<- size_sim1_n60[,-1]
MU1_sim1_n60<- MU1_sim1_n60[,-1]
MU2_sim1_n60<- MU2_sim1_n60[,-1]
V_M_sim1_n60<- V_M_sim1_n60[,-1]
elapsed_sim1_n60<- elapsed_sim1_n60[,-1]

#######################################################################################################################################
P_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/P_sim2_n120.csv")
Phi_sim2_n120 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/Phi_sim2_n120.csv")
overdisp_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/overdisp_sim2_n120.csv")
size_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/size_sim2_n120.csv")
MU1_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU1_sim2_n120.csv")
MU2_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU2_sim2_n120.csv")
V_M_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/v_M_sim2_n120.csv")
elapsed_sim2_n120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/elapsed_sim2_n120.csv")
######################################################################################################################################
P_sim2_n120<- P_sim2_n120[,-1]
Phi_sim2_n120<- Phi_sim2_n120[,-1]
overdisp_sim2_n120<- overdisp_sim2_n120[,-1]
size_sim2_n120<- size_sim2_n120[,-1]
MU1_sim2_n120<- MU1_sim2_n120[,-1]
MU2_sim2_n120<- MU2_sim2_n120[,-1]
V_M_sim2_n120<- V_M_sim2_n120[,-1]
elapsed_sim2_n120<- elapsed_sim2_n120[,-1]

#######################################################################################################################################
P_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/P_sim3_n300.csv")
Phi_sim3_n300 <- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/Phi_sim3_n300.csv")
overdisp_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/overdisp_sim3_n300.csv")
size_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/size_sim3_n300.csv")
MU1_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU1_sim3_n300.csv")
MU2_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU2_sim3_n300.csv")
V_M_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/v_M_sim3_n300.csv")
elapsed_sim3_n300<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/elapsed_sim3_n300.csv")
######################################################################################################################################
P_sim3_n300<- P_sim3_n300[,-1]
Phi_sim3_n300<- Phi_sim3_n300[,-1]
overdisp_sim3_n300<- overdisp_sim3_n300[,-1]
size_sim3_n300<- size_sim3_n300[,-1]
MU1_sim3_n300<- MU1_sim3_n300[,-1]
MU2_sim3_n300<- MU2_sim3_n300[,-1]
V_M_sim3_n300<- V_M_sim3_n300[,-1]
elapsed_sim3_n300<- elapsed_sim3_n300[,-1]

#######################################################################################################################################
#######################################################################################################################################

P_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/P_sim4_n600.csv")
Phi_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/Phi_sim4_n600.csv")
overdisp_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/overdisp_sim4_n600.csv")
size_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/size_sim4_n600.csv")
MU1_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU1_sim4_n600.csv")
MU2_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU2_sim4_n600.csv")
V_M_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/v_M_sim4_n600.csv")
elapsed_sim4_n600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/elapsed_sim4_n600.csv")

P_sim4_n600<- P_sim4_n600[,-1]
Phi_sim4_n600<- Phi_sim4_n600[,-1]
overdisp_sim4_n600<- overdisp_sim4_n600[,-1]
size_sim4_n600<- size_sim4_n600[,-1]
MU1_sim4_n600<- MU1_sim4_n600[,-1]
MU2_sim4_n600<- MU2_sim4_n600[,-1]
V_M_sim4_n600<- V_M_sim4_n600[,-1]
elapsed_sim4_n600<- elapsed_sim4_n600[,-1]

#############################################################################################################################



P_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/P_sim5_n1200.csv")
Phi_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/Phi_sim5_n1200.csv")
overdisp_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/overdisp_sim5_n1200.csv")
size_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/size_sim5_n1200.csv")
MU1_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU1_sim5_n1200.csv")
MU2_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/MU2_sim5_n1200.csv")
V_M_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/v_M_sim5_n1200.csv")
elapsed_sim5_n1200<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario9/elapsed_sim5_n1200.csv")

P_sim5_n1200<- P_sim5_n1200[,-1]
Phi_sim5_n1200<- Phi_sim5_n1200[,-1]
overdisp_sim5_n1200<- overdisp_sim5_n1200[,-1]
size_sim5_n1200<- size_sim5_n1200[,-1]
MU1_sim5_n1200<- MU1_sim5_n1200[,-1]
MU2_sim5_n1200<- MU2_sim5_n1200[,-1]
V_M_sim5_n1200<- V_M_sim5_n1200[,-1]
elapsed_sim5_n1200<- elapsed_sim5_n1200[,-1]
###########################################################################################################################
#size_sim1_n60
#size_sim2_n120
#size_sim3_n300
#size_sim5_n1200
#############################################################################################################################
#############################################################################################################################
par(mfrow=c(2,2))
boxplot(size_sim1_n60[,1],size_sim2_n120[,1],size_sim3_n300[,1],size_sim4_n600[,1],size_sim5_n1200[,1],main=expression(nu[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=5)

boxplot(size_sim1_n60[,2],size_sim2_n120[,2],size_sim3_n300[,2],size_sim4_n600[,2],size_sim5_n1200[,2],main=expression(nu[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=20)

boxplot(size_sim1_n60[,1],size_sim2_n120[,1],size_sim3_n300[,1],size_sim4_n600[,1],size_sim5_n1200[,1],main=expression(nu[1]),outline =FALSE,xlab="N_rm_oultiler",names=c(60,120,300,600,1200))
abline(h=5)

boxplot(size_sim1_n60[,2],size_sim2_n120[,2],size_sim3_n300[,2],size_sim4_n600[,2],size_sim5_n1200[,2],main=expression(nu[2]),outline = FALSE,xlab="N_rm_outlier",names=c(60,120,300,600,1200))
abline(h=20)

#################################################################################################################################
par(mfrow=c(2,2))
boxplot(P_sim1_n60[,1],P_sim2_n120[,1],P_sim3_n300[,1],P_sim4_n600[,1],P_sim5_n1200[,1],main=expression(pi[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.5)

boxplot(P_sim1_n60[,2],P_sim2_n120[,2],P_sim3_n300[,2],P_sim4_n600[,2],P_sim5_n1200[,2],main=expression(pi[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.5)

############################################################################################################################
#par(mfrow=c(2,2))
boxplot(Phi_sim1_n60[,1],Phi_sim2_n120[,1],Phi_sim3_n300[,1],Phi_sim4_n600[,1],Phi_sim5_n1200[,1],main=expression(phi[1]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.1)

boxplot(Phi_sim1_n60[,2],Phi_sim2_n120[,2],Phi_sim3_n300[,2],Phi_sim4_n600[,2],Phi_sim5_n1200[,2],main=expression(phi[2]),xlab="N",names=c(60,120,300,600,1200))
abline(h=0.1)

############################################################################################################################
#par(mfrow=c(1,2))
boxplot(V_M_sim1_n60,V_M_sim2_n120,V_M_sim3_n300,V_M_sim4_n600,V_M_sim5_n1200,main="V-Measures",xlab="N",names=c(60,120,300,600,1200))
abline(h=1)



#################################################################################################################################
MSE_MU1_est<- c(mean(MU1_sim1_n60),mean(MU1_sim2_n120),mean(MU1_sim3_n300),mean(MU1_sim4_n600),mean(MU1_sim5_n1200))
paste("MSE_MU_hat1:",MSE_MU1_est)
print(MSE_MU1_est)
MSE_MU2_est<- c(mean(MU2_sim1_n60),mean(MU2_sim2_n120),mean(MU2_sim3_n300),mean(MU2_sim4_n600),mean(MU2_sim5_n1200))
paste("MSE_MU_hat2:",MSE_MU2_est)
print(MSE_MU2_est)
#################################################################################################################
MSE_Size1_60<- mean((size_sim1_n60[,1]-5)^2)
MSE_Size1_120<- mean((size_sim2_n120[,1]-5)^2)
MSE_Size1_300<- mean((size_sim3_n300[,1]-5)^2)
MSE_Size1_600<- mean((size_sim4_n600[,1]-5)^2)
MSE_Size1_1200<- mean((size_sim5_n1200[,1]-5)^2)
MSE_1<- c(MSE_Size1_60,MSE_Size1_120,MSE_Size1_300,MSE_Size1_600,MSE_Size1_1200)
###For size
print(MSE_1)

MSE_Size2_60<- mean((size_sim1_n60[,2]-20)^2)
MSE_Size2_120<- mean((size_sim2_n120[,2]-20)^2)
MSE_Size2_300<- mean((size_sim3_n300[,2]-20)^2)
MSE_Size2_600<- mean((size_sim4_n600[,2]-20)^2)
MSE_Size2_1200<- mean((size_sim5_n1200[,2]-20)^2)
MSE_2<- c(MSE_Size2_60,MSE_Size2_120,MSE_Size2_300,MSE_Size2_600,MSE_Size2_1200)
print(MSE_2)

#MSE_S<- rbind(MSE_1,MSE_2)
#colnames(MSE_S)<- c(60,120,300,600,1200)
#MSE_S

##################################################################################################################
# 
# MAD_Size1_60<- median(abs(size_sim1_n60[,1]-5))
# MAD_Size1_120<- median(abs(size_sim2_n120[,1]-5))
# MAD_Size1_300<- median(abs(size_sim3_n300[,1]-5))
# MAD_Size1_600<- median(abs(size_sim4_n600[,1]-5))
# MAD_Size1_1200<- median(abs(size_sim4_n1200[,1]-5))
# MAD_1<- c(MAD_Size1_60,MAD_Size1_120,MAD_Size1_300,MAD_Size1_600,MAD_Size1_1200)
# MAD_1
# 
# MAD_Size2_60<- median(abs(size_sim1_n60[,2]-5))
# MAD_Size2_120<- median(abs(size_sim2_n120[,2]-5))
# MAD_Size2_300<- median(abs(size_sim3_n300[,2]-5))
# MAD_Size2_600<- median(abs(size_sim4_n600[,2]-5))
# MAD_Size2_1200<- median(abs(size_sim5_n1200[,2]-5))
# MAD_2<- c(MAD_Size2_60,MAD_Size2_120,MAD_Size2_300,MAD_Size2_600,MAD_Size2_1200)
# MAD_2
# 
# MAD_S<- rbind(MAD_1,MAD_2)
# colnames(MAD_S)<- c(60,120,300,600,1200)
# MAD_S
# 



```


# Vary G RESULTS

## Scenario 1: Size(10,100), Function: disp_para

```{r Sc1,eval=TRUE,echo=FALSE}

############################################################################################################################################
P_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/P_sim1_G12.csv")
Phi_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/Phi_sim1_G12.csv")
overdisp_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/overdisp_sim1_G12.csv")
size_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/size_sim1_G12.csv")
MU1_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU1_sim1_G12.csv")
MU2_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU2_sim1_G12.csv")
V_M_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/v_M_sim1_G12.csv")
elapsed_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/elapsed_sim1_G12.csv")
#########################################################################################################################################
P_sim1_G12<- P_sim1_G12[,-1]
Phi_sim1_G12<- Phi_sim1_G12[,-1]
overdisp_sim1_G12<- overdisp_sim1_G12[,-1]
size_sim1_G12<- size_sim1_G12[,-1]
MU1_sim1_G12<- MU1_sim1_G12[,-1]
MU2_sim1_G12<- MU2_sim1_G12[,-1]
V_M_sim1_G12<- V_M_sim1_G12[,-1]
elapsed_sim1_G12<- elapsed_sim1_G12[,-1]
#############################################################################################################################################

P_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/P_sim2_G60.csv")
Phi_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/Phi_sim2_G60.csv")
overdisp_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/overdisp_sim2_G60.csv")
size_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/size_sim2_G60.csv")
MU1_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU1_sim2_G60.csv")
MU2_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU2_sim2_G60.csv")
V_M_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/v_M_sim2_G60.csv")
elapsed_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/elapsed_sim2_G60.csv")
#########################################################################################################################################
P_sim2_G60<- P_sim2_G60[,-1]
Phi_sim2_G60<- Phi_sim2_G60[,-1]
overdisp_sim2_G60<- overdisp_sim2_G60[,-1]
size_sim2_G60<- size_sim2_G60[,-1]
MU1_sim2_G60<- MU1_sim2_G60[,-1]
MU2_sim2_G60<- MU2_sim2_G60[,-1]
V_M_sim2_G60<- V_M_sim2_G60[,-1]
elapsed_sim2_G60<- elapsed_sim2_G60[,-1]
#############################################################################################################################################
P_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/P_sim3_G120.csv")
Phi_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/Phi_sim3_G120.csv")
overdisp_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/overdisp_sim3_G120.csv")
size_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/size_sim3_G120.csv")
MU1_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU1_sim3_G120.csv")
MU2_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU2_sim3_G120.csv")
V_M_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/v_M_sim3_G120.csv")
elapsed_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/elapsed_sim3_G120.csv")
#########################################################################################################################################
P_sim3_G120<- P_sim3_G120[,-1]
Phi_sim3_G120<- Phi_sim3_G120[,-1]
overdisp_sim3_G120<- overdisp_sim3_G120[,-1]
size_sim3_G120<- size_sim3_G120[,-1]
MU1_sim3_G120<- MU1_sim3_G120[,-1]
MU2_sim3_G120<- MU2_sim3_G120[,-1]
V_M_sim3_G120<- V_M_sim3_G120[,-1]
elapsed_sim3_G120<- elapsed_sim3_G120[,-1]
#############################################################################################################################################


############################################################################################################################################
P_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/P_sim4_G600.csv")
Phi_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/Phi_sim4_G600.csv")
overdisp_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/overdisp_sim4_G600.csv")
size_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/size_sim4_G600.csv")
MU1_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU1_sim4_G600.csv")
MU2_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU2_sim4_G600.csv")
V_M_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/v_M_sim4_G600.csv")
elapsed_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/elapsed_sim4_G600.csv")
#########################################################################################################################################
P_sim4_G600<- P_sim4_G600[,-1]
Phi_sim4_G600<- Phi_sim4_G600[,-1]
overdisp_sim4_G600<- overdisp_sim4_G600[,-1]
size_sim4_G600<- size_sim4_G600[,-1]
MU1_sim4_G600<- MU1_sim4_G600[,-1]
MU2_sim4_G600<- MU2_sim4_G600[,-1]
V_M_sim4_G600<- V_M_sim4_G600[,-1]
elapsed_sim4_G600<- elapsed_sim4_G600[,-1]
#############################################################################################################################################
##############################################################################################################################################

############################################################################################################################################
P_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/P_sim5_G1500.csv")
Phi_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/Phi_sim5_G1500.csv")
overdisp_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/overdisp_sim5_G1500.csv")
size_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/size_sim5_G1500.csv")
MU1_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU1_sim5_G1500.csv")
MU2_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/MU2_sim5_G1500.csv")
V_M_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/v_M_sim5_G1500.csv")
elapsed_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario1/elapsed_sim5_G1500.csv")
#########################################################################################################################################
P_sim5_G1500<- P_sim5_G1500[,-1]
Phi_sim5_G1500<- Phi_sim5_G1500[,-1]
overdisp_sim5_G1500<- overdisp_sim5_G1500[,-1]
size_sim5_G1500<- size_sim5_G1500[,-1]
MU1_sim5_G1500<- MU1_sim5_G1500[,-1]
MU2_sim5_G1500<- MU2_sim5_G1500[,-1]
V_M_sim5_G1500<- V_M_sim5_G1500[,-1]
elapsed_sim5_G1500<- elapsed_sim5_G1500[,-1]
#############################################################################################################################################
##############################################################################################################################################
### PLOTS###
###Pi###
par(mfrow=c(2,2))

boxplot(P_sim1_G12[,1],P_sim2_G60[,1],P_sim3_G120[,1],P_sim4_G600[,1],P_sim5_G1500[,1],main=expression(pi[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.5,col="Red",lty=3)

boxplot(P_sim1_G12[,2],P_sim2_G60[,2],P_sim3_G120[,2],P_sim4_G600[,2],P_sim5_G1500[,2],main=expression(pi[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.5,col="Red",lty=3)
##############################################################################################################################################
###Phi###
#par(mfrow=c(1,2))
boxplot(Phi_sim1_G12[,1],Phi_sim2_G60[,1],Phi_sim3_G120[,1],Phi_sim4_G600[,1],Phi_sim5_G1500[,1],main=expression(phi[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.1,col="Red",lty=3)

boxplot(Phi_sim1_G12[,2],Phi_sim2_G60[,2],Phi_sim3_G120[,2],Phi_sim4_G600[,2],Phi_sim5_G1500[,2],main=expression(phi[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.1,col="Red",lty=3)

##############################################################################################################################################
###V_means###
boxplot(V_M_sim1_G12, V_M_sim2_G60, V_M_sim3_G120, V_M_sim4_G600,main="V-Measures",xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=1,col="Red",lty=3)

##############################################################################################################################################
###size###
par(mfrow=c(2,2))
boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],size_sim5_G1500[,1],main=expression(nu[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=10,col="Red",lty=3)

boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],size_sim5_G1500[,2],main=expression(nu[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=100,col="Red",lty=3)

boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],size_sim5_G1500[,1],main=expression(nu[1]),outline = FALSE,xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=10,col="Red",lty=3)

boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],size_sim5_G1500[,2],main=expression(nu[2]),outline = FALSE,xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=100,col="Red",lty=3)
##############################################################################################################################################################
###overdispersion###
# par(mfrow=c(1,2))
# boxplot(overdisp_sim1_G12[,1],overdisp_sim2_G60[,1],overdisp_sim3_G120[,1],overdisp_sim4_G600[,1],main=expression(alpha[1]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
# abline(h=1/5,col="Red",lty=3)
# 
# boxplot(overdisp_sim1_G12[,2],overdisp_sim2_G60[,2],overdisp_sim3_G120[,2],overdisp_sim4_G600[,2],main=expression(alpha[2]),xlab="G",names=c(12,60,120,600),cex.axis=0.7,ylim=c(0.095,0.15))
# abline(h=1/10,col="Red",lty=3)
# ###############################################################################################################################################
# ### Compute time###
# boxplot(elapsed_sim1_G12,elapsed_sim2_G60,elapsed_sim3_G120,elapsed_sim4_G600,main="Compute_time",xlab="G",names=c(12,60,120,600),cex.axis=0.7)

##############################################################################################################################################
# ### Tables###
# ### Pi###
# k<- c(rep(1,4),rep(2,4))
# A<- rep(c(12,60,120,600),2)
# B<- c(mean(P_sim1_G12[,1]),mean(P_sim2_G60[,1]),mean(P_sim3_G120[,1]),mean(P_sim4_G600[,1]),mean(P_sim5_G1500[,1])) 
# C<- c(sd(P_sim1_G12[,1]),sd(P_sim2_G60[,1]),sd(P_sim3_G120[,1]),sd(P_sim4_G600[,1])) 
# D<- c(mean(P_sim1_G12[,2]),mean(P_sim2_G60[,2]),mean(P_sim3_G120[,2]),mean(P_sim4_G600[,2]),mean(P_sim5_G1500[,2])) 
# E<- c(sd(P_sim1_G12[,2]),sd(P_sim2_G60[,2]),sd(P_sim3_G120[,2]),sd(P_sim4_G600[,2])) 
# 
# tab_P<- rbind(cbind(B,C),cbind(D,E))
# tab_P1<- cbind(k,A,tab_P)
# 
# colnames(tab_P1)<- c("k","G","Mean","SE")
# tab_P1
# ##############################################################################################################################################
# ### Phi###
# kk<- c(rep(1,4),rep(2,4))
# AA<- rep(c(12,60,120,600),2)
# BB<- c(mean(Phi_sim1_G12[,1]),mean(Phi_sim2_G60[,1]),mean(Phi_sim3_G120[,1]),mean(Phi_sim4_G600[,1])) 
# CC<- c(sd(Phi_sim1_G12[,1]),sd(Phi_sim2_G60[,1]),sd(Phi_sim3_G120[,1]),sd(Phi_sim4_G600[,1])) 
# DD<- c(mean(Phi_sim1_G12[,2]),mean(Phi_sim2_G60[,2]),mean(Phi_sim3_G120[,2]),mean(Phi_sim4_G600[,2])) 
# EE<- c(sd(Phi_sim1_G12[,2]),sd(Phi_sim2_G60[,2]),sd(Phi_sim3_G120[,2]),sd(Phi_sim4_G600[,2])) 
# 
# tab_Phi<- rbind(cbind(BB,CC),cbind(DD,EE))
# tab_Phi1<- cbind(kk,AA,tab_Phi)
# 
# colnames(tab_Phi1)<- c("k","G","Mean","SE")
# tab_Phi1
# 
# ##############################################################################################################################################
# xtable::xtable(tab_P1,digits = 5)
# xtable::xtable(tab_Phi1,digits = 5)
################################################################################################################################################
### MU###
mu_k1<- c(1,mean(MU1_sim1_G12),mean(MU1_sim2_G60),mean(MU1_sim3_G120),mean(MU1_sim4_G600),mean(MU1_sim5_G1500))
mu_k2<- c(2,mean(MU2_sim1_G12),mean(MU2_sim2_G60),mean(MU2_sim3_G120),mean(MU2_sim4_G600),mean(MU2_sim5_G1500))
#mu_k1
#mu_k2
#k<- c(1,2)
tab_mu<- rbind(mu_k1,mu_k2)
colnames(tab_mu)<- c("G",12,60,120,600,1500)
print(tab_mu)
# xtable::xtable(tab_mu,digits = 5)
###########################################################################################################################################
# ### Computeing time###
# k<- c(12,60,120,600)
# M<- c(mean(elapsed_sim1_G12),mean(elapsed_sim2_G60),mean(elapsed_sim3_G120),mean(elapsed_sim4_G600))
# S<- c(sd(elapsed_sim1_G12),sd(elapsed_sim2_G60),sd(elapsed_sim3_G120),sd(elapsed_sim4_G600))
# tab_compute<- cbind(k,M,S)
# colnames(tab_compute)<- c("G","Mean","SE")
# tab_compute
# xtable::xtable(tab_compute)
# ##############################################################################################################################################
# ### Size###
# #mean((size_sim1_G12[,1]-5)^2)
# #mean((size_sim2_G60[,1]-5)^2)
# #mean((size_sim3_G120[,1]-5)^2)
# #mean((size_sim4_G600[,1]-5)^2)
# 
# size_k1<- c(1,mean(abs(size_sim1_G12[,1]-5)),mean(abs(size_sim2_G60[,1]-5)),mean(abs(size_sim3_G120[,1]-5)),mean(abs(size_sim4_G600[,1]-5)))
# 
# #mean((size_sim1_G12[,2]-10)^2)
# #mean((size_sim2_G60[,2]-10)^2)
# #mean((size_sim3_G120[,2]-10)^2)
# #mean((size_sim4_G600[,2]-10)^2)
# 
# size_k2<- c(2,mean(abs(size_sim1_G12[,2]-10)),mean(abs(size_sim2_G60[,2]-10)),mean(abs(size_sim3_G120[,2]-10)),mean(abs(size_sim4_G600[,2]-10)))
# 
# tab_size<- rbind(size_k1,size_k2)
# colnames(tab_size)<- c("k",12,60,120,600)
# tab_size
# xtable::xtable(tab_size,digits = 6)
# ########################################################################################################################
# ### Overdispersion###
# 
# mean(abs(overdisp_sim1_G12[,1]-5))
# mean(abs(overdisp_sim2_G60[,1]-5))
# mean(abs(overdisp_sim3_G120[,1]-5))
# mean(abs(overdisp_sim4_G600[,1]-5))
# 
# #mean((size_sim1_G12[,2]-10)^2)
# #mean((size_sim2_G60[,2]-10)^2)
# #mean((size_sim3_G120[,2]-10)^2)
# #mean((size_sim4_G600[,2]-10)^2)
# 
# 
# mean(abs(overdisp_sim1_G12[,2]-10))
# mean(abs(overdisp_sim2_G60[,2]-10))
# mean(abs(overdisp_sim3_G120[,2]-10))
# mean(abs(overdisp_sim4_G600[,2]-10))
# 


```

## Scenario 2: Size(5,20), Function: disp_para

```{r Sc2,eval=TRUE,echo=FALSE}

############################################################################################################################################
P_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/P_sim1_G12.csv")
Phi_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/Phi_sim1_G12.csv")
overdisp_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/overdisp_sim1_G12.csv")
size_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/size_sim1_G12.csv")
MU1_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU1_sim1_G12.csv")
MU2_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU2_sim1_G12.csv")
V_M_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/v_M_sim1_G12.csv")
elapsed_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/elapsed_sim1_G12.csv")
#########################################################################################################################################
P_sim1_G12<- P_sim1_G12[,-1]
Phi_sim1_G12<- Phi_sim1_G12[,-1]
overdisp_sim1_G12<- overdisp_sim1_G12[,-1]
size_sim1_G12<- size_sim1_G12[,-1]
MU1_sim1_G12<- MU1_sim1_G12[,-1]
MU2_sim1_G12<- MU2_sim1_G12[,-1]
V_M_sim1_G12<- V_M_sim1_G12[,-1]
elapsed_sim1_G12<- elapsed_sim1_G12[,-1]
#############################################################################################################################################

P_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/P_sim2_G60.csv")
Phi_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/Phi_sim2_G60.csv")
overdisp_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/overdisp_sim2_G60.csv")
size_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/size_sim2_G60.csv")
MU1_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU1_sim2_G60.csv")
MU2_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU2_sim2_G60.csv")
V_M_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/v_M_sim2_G60.csv")
elapsed_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/elapsed_sim2_G60.csv")
#########################################################################################################################################
P_sim2_G60<- P_sim2_G60[,-1]
Phi_sim2_G60<- Phi_sim2_G60[,-1]
overdisp_sim2_G60<- overdisp_sim2_G60[,-1]
size_sim2_G60<- size_sim2_G60[,-1]
MU1_sim2_G60<- MU1_sim2_G60[,-1]
MU2_sim2_G60<- MU2_sim2_G60[,-1]
V_M_sim2_G60<- V_M_sim2_G60[,-1]
elapsed_sim2_G60<- elapsed_sim2_G60[,-1]
#############################################################################################################################################
P_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/P_sim3_G120.csv")
Phi_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/Phi_sim3_G120.csv")
overdisp_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/overdisp_sim3_G120.csv")
size_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/size_sim3_G120.csv")
MU1_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU1_sim3_G120.csv")
MU2_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU2_sim3_G120.csv")
V_M_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/v_M_sim3_G120.csv")
elapsed_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/elapsed_sim3_G120.csv")
#########################################################################################################################################
P_sim3_G120<- P_sim3_G120[,-1]
Phi_sim3_G120<- Phi_sim3_G120[,-1]
overdisp_sim3_G120<- overdisp_sim3_G120[,-1]
size_sim3_G120<- size_sim3_G120[,-1]
MU1_sim3_G120<- MU1_sim3_G120[,-1]
MU2_sim3_G120<- MU2_sim3_G120[,-1]
V_M_sim3_G120<- V_M_sim3_G120[,-1]
elapsed_sim3_G120<- elapsed_sim3_G120[,-1]
#############################################################################################################################################


############################################################################################################################################
P_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/P_sim4_G600.csv")
Phi_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/Phi_sim4_G600.csv")
overdisp_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/overdisp_sim4_G600.csv")
size_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/size_sim4_G600.csv")
MU1_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU1_sim4_G600.csv")
MU2_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU2_sim4_G600.csv")
V_M_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/v_M_sim4_G600.csv")
elapsed_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/elapsed_sim4_G600.csv")
#########################################################################################################################################
P_sim4_G600<- P_sim4_G600[,-1]
Phi_sim4_G600<- Phi_sim4_G600[,-1]
overdisp_sim4_G600<- overdisp_sim4_G600[,-1]
size_sim4_G600<- size_sim4_G600[,-1]
MU1_sim4_G600<- MU1_sim4_G600[,-1]
MU2_sim4_G600<- MU2_sim4_G600[,-1]
V_M_sim4_G600<- V_M_sim4_G600[,-1]
elapsed_sim4_G600<- elapsed_sim4_G600[,-1]
#############################################################################################################################################
##############################################################################################################################################

############################################################################################################################################
P_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/P_sim5_G1500.csv")
Phi_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/Phi_sim5_G1500.csv")
overdisp_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/overdisp_sim5_G1500.csv")
size_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/size_sim5_G1500.csv")
MU1_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU1_sim5_G1500.csv")
MU2_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/MU2_sim5_G1500.csv")
V_M_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/v_M_sim5_G1500.csv")
elapsed_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario2/elapsed_sim5_G1500.csv")
#########################################################################################################################################
P_sim5_G1500<- P_sim5_G1500[,-1]
Phi_sim5_G1500<- Phi_sim5_G1500[,-1]
overdisp_sim5_G1500<- overdisp_sim5_G1500[,-1]
size_sim5_G1500<- size_sim5_G1500[,-1]
MU1_sim5_G1500<- MU1_sim5_G1500[,-1]
MU2_sim5_G1500<- MU2_sim5_G1500[,-1]
V_M_sim5_G1500<- V_M_sim5_G1500[,-1]
elapsed_sim5_G1500<- elapsed_sim5_G1500[,-1]
#############################################################################################################################################
##############################################################################################################################################
### PLOTS###
###Pi###
par(mfrow=c(2,2))

boxplot(P_sim1_G12[,1],P_sim2_G60[,1],P_sim3_G120[,1],P_sim4_G600[,1],P_sim5_G1500[,1],main=expression(pi[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.5,col="Red",lty=3)

boxplot(P_sim1_G12[,2],P_sim2_G60[,2],P_sim3_G120[,2],P_sim4_G600[,2],P_sim5_G1500[,2],main=expression(pi[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.5,col="Red",lty=3)
##############################################################################################################################################
###Phi###
#par(mfrow=c(1,2))
boxplot(Phi_sim1_G12[,1],Phi_sim2_G60[,1],Phi_sim3_G120[,1],Phi_sim4_G600[,1],Phi_sim5_G1500[,1],main=expression(phi[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.1,col="Red",lty=3)

boxplot(Phi_sim1_G12[,2],Phi_sim2_G60[,2],Phi_sim3_G120[,2],Phi_sim4_G600[,2],Phi_sim5_G1500[,2],main=expression(phi[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.1,col="Red",lty=3)

##############################################################################################################################################
###V_means###
boxplot(V_M_sim1_G12, V_M_sim2_G60, V_M_sim3_G120, V_M_sim4_G600,main="V-Measures",xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=1,col="Red",lty=3)

##############################################################################################################################################
###size###
par(mfrow=c(2,2))
boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],size_sim5_G1500[,1],main=expression(nu[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=5,col="Red",lty=3)

boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],size_sim5_G1500[,2],main=expression(nu[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=20,col="Red",lty=3)

boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],size_sim5_G1500[,1],main=expression(nu[1]),outline = FALSE,xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=5,col="Red",lty=3)

boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],size_sim5_G1500[,2],main=expression(nu[2]),outline = FALSE,xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=20,col="Red",lty=3)
##############################################################################################################################################################
###overdispersion###
# par(mfrow=c(1,2))
# boxplot(overdisp_sim1_G12[,1],overdisp_sim2_G60[,1],overdisp_sim3_G120[,1],overdisp_sim4_G600[,1],main=expression(alpha[1]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
# abline(h=1/5,col="Red",lty=3)
# 
# boxplot(overdisp_sim1_G12[,2],overdisp_sim2_G60[,2],overdisp_sim3_G120[,2],overdisp_sim4_G600[,2],main=expression(alpha[2]),xlab="G",names=c(12,60,120,600),cex.axis=0.7,ylim=c(0.095,0.15))
# abline(h=1/10,col="Red",lty=3)
# ###############################################################################################################################################
# ### Compute time###
# boxplot(elapsed_sim1_G12,elapsed_sim2_G60,elapsed_sim3_G120,elapsed_sim4_G600,main="Compute_time",xlab="G",names=c(12,60,120,600),cex.axis=0.7)

##############################################################################################################################################
# ### Tables###
# ### Pi###
# k<- c(rep(1,4),rep(2,4))
# A<- rep(c(12,60,120,600),2)
# B<- c(mean(P_sim1_G12[,1]),mean(P_sim2_G60[,1]),mean(P_sim3_G120[,1]),mean(P_sim4_G600[,1]),mean(P_sim5_G1500[,1])) 
# C<- c(sd(P_sim1_G12[,1]),sd(P_sim2_G60[,1]),sd(P_sim3_G120[,1]),sd(P_sim4_G600[,1])) 
# D<- c(mean(P_sim1_G12[,2]),mean(P_sim2_G60[,2]),mean(P_sim3_G120[,2]),mean(P_sim4_G600[,2]),mean(P_sim5_G1500[,2])) 
# E<- c(sd(P_sim1_G12[,2]),sd(P_sim2_G60[,2]),sd(P_sim3_G120[,2]),sd(P_sim4_G600[,2])) 
# 
# tab_P<- rbind(cbind(B,C),cbind(D,E))
# tab_P1<- cbind(k,A,tab_P)
# 
# colnames(tab_P1)<- c("k","G","Mean","SE")
# tab_P1
# ##############################################################################################################################################
# ### Phi###
# kk<- c(rep(1,4),rep(2,4))
# AA<- rep(c(12,60,120,600),2)
# BB<- c(mean(Phi_sim1_G12[,1]),mean(Phi_sim2_G60[,1]),mean(Phi_sim3_G120[,1]),mean(Phi_sim4_G600[,1])) 
# CC<- c(sd(Phi_sim1_G12[,1]),sd(Phi_sim2_G60[,1]),sd(Phi_sim3_G120[,1]),sd(Phi_sim4_G600[,1])) 
# DD<- c(mean(Phi_sim1_G12[,2]),mean(Phi_sim2_G60[,2]),mean(Phi_sim3_G120[,2]),mean(Phi_sim4_G600[,2])) 
# EE<- c(sd(Phi_sim1_G12[,2]),sd(Phi_sim2_G60[,2]),sd(Phi_sim3_G120[,2]),sd(Phi_sim4_G600[,2])) 
# 
# tab_Phi<- rbind(cbind(BB,CC),cbind(DD,EE))
# tab_Phi1<- cbind(kk,AA,tab_Phi)
# 
# colnames(tab_Phi1)<- c("k","G","Mean","SE")
# tab_Phi1
# 
# ##############################################################################################################################################
# xtable::xtable(tab_P1,digits = 5)
# xtable::xtable(tab_Phi1,digits = 5)
################################################################################################################################################
### MU###
mu_k1<- c(1,mean(MU1_sim1_G12),mean(MU1_sim2_G60),mean(MU1_sim3_G120),mean(MU1_sim4_G600),mean(MU1_sim5_G1500))
mu_k2<- c(2,mean(MU2_sim1_G12),mean(MU2_sim2_G60),mean(MU2_sim3_G120),mean(MU2_sim4_G600),mean(MU2_sim5_G1500))
#mu_k1
#mu_k2
#k<- c(1,2)
tab_mu<- rbind(mu_k1,mu_k2)
colnames(tab_mu)<- c("G",12,60,120,600,1500)
print(tab_mu)
# xtable::xtable(tab_mu,digits = 5)
###########################################################################################################################################
# ### Computeing time###
# k<- c(12,60,120,600)
# M<- c(mean(elapsed_sim1_G12),mean(elapsed_sim2_G60),mean(elapsed_sim3_G120),mean(elapsed_sim4_G600))
# S<- c(sd(elapsed_sim1_G12),sd(elapsed_sim2_G60),sd(elapsed_sim3_G120),sd(elapsed_sim4_G600))
# tab_compute<- cbind(k,M,S)
# colnames(tab_compute)<- c("G","Mean","SE")
# tab_compute
# xtable::xtable(tab_compute)
# ##############################################################################################################################################
# ### Size###
# #mean((size_sim1_G12[,1]-5)^2)
# #mean((size_sim2_G60[,1]-5)^2)
# #mean((size_sim3_G120[,1]-5)^2)
# #mean((size_sim4_G600[,1]-5)^2)
# 
# size_k1<- c(1,mean(abs(size_sim1_G12[,1]-5)),mean(abs(size_sim2_G60[,1]-5)),mean(abs(size_sim3_G120[,1]-5)),mean(abs(size_sim4_G600[,1]-5)))
# 
# #mean((size_sim1_G12[,2]-10)^2)
# #mean((size_sim2_G60[,2]-10)^2)
# #mean((size_sim3_G120[,2]-10)^2)
# #mean((size_sim4_G600[,2]-10)^2)
# 
# size_k2<- c(2,mean(abs(size_sim1_G12[,2]-10)),mean(abs(size_sim2_G60[,2]-10)),mean(abs(size_sim3_G120[,2]-10)),mean(abs(size_sim4_G600[,2]-10)))
# 
# tab_size<- rbind(size_k1,size_k2)
# colnames(tab_size)<- c("k",12,60,120,600)
# tab_size
# xtable::xtable(tab_size,digits = 6)
# ########################################################################################################################
# ### Overdispersion###
# 
# mean(abs(overdisp_sim1_G12[,1]-5))
# mean(abs(overdisp_sim2_G60[,1]-5))
# mean(abs(overdisp_sim3_G120[,1]-5))
# mean(abs(overdisp_sim4_G600[,1]-5))
# 
# #mean((size_sim1_G12[,2]-10)^2)
# #mean((size_sim2_G60[,2]-10)^2)
# #mean((size_sim3_G120[,2]-10)^2)
# #mean((size_sim4_G600[,2]-10)^2)
# 
# 
# mean(abs(overdisp_sim1_G12[,2]-10))
# mean(abs(overdisp_sim2_G60[,2]-10))
# mean(abs(overdisp_sim3_G120[,2]-10))
# mean(abs(overdisp_sim4_G600[,2]-10))
# 


```


## Scenario 3: Size(10,100), Function: glm.nb

```{r Sc3,eval=TRUE,echo=FALSE}

############################################################################################################################################
P_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/P_sim1_G12.csv")
Phi_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/Phi_sim1_G12.csv")
overdisp_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/overdisp_sim1_G12.csv")
size_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/size_sim1_G12.csv")
MU1_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU1_sim1_G12.csv")
MU2_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU2_sim1_G12.csv")
V_M_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/v_M_sim1_G12.csv")
elapsed_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/elapsed_sim1_G12.csv")
#########################################################################################################################################
P_sim1_G12<- P_sim1_G12[,-1]
Phi_sim1_G12<- Phi_sim1_G12[,-1]
overdisp_sim1_G12<- overdisp_sim1_G12[,-1]
size_sim1_G12<- size_sim1_G12[,-1]
MU1_sim1_G12<- MU1_sim1_G12[,-1]
MU2_sim1_G12<- MU2_sim1_G12[,-1]
V_M_sim1_G12<- V_M_sim1_G12[,-1]
elapsed_sim1_G12<- elapsed_sim1_G12[,-1]
#############################################################################################################################################

P_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/P_sim2_G60.csv")
Phi_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/Phi_sim2_G60.csv")
overdisp_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/overdisp_sim2_G60.csv")
size_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/size_sim2_G60.csv")
MU1_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU1_sim2_G60.csv")
MU2_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU2_sim2_G60.csv")
V_M_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/v_M_sim2_G60.csv")
elapsed_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/elapsed_sim2_G60.csv")
#########################################################################################################################################
P_sim2_G60<- P_sim2_G60[,-1]
Phi_sim2_G60<- Phi_sim2_G60[,-1]
overdisp_sim2_G60<- overdisp_sim2_G60[,-1]
size_sim2_G60<- size_sim2_G60[,-1]
MU1_sim2_G60<- MU1_sim2_G60[,-1]
MU2_sim2_G60<- MU2_sim2_G60[,-1]
V_M_sim2_G60<- V_M_sim2_G60[,-1]
elapsed_sim2_G60<- elapsed_sim2_G60[,-1]
#############################################################################################################################################
P_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/P_sim3_G120.csv")
Phi_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/Phi_sim3_G120.csv")
overdisp_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/overdisp_sim3_G120.csv")
size_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/size_sim3_G120.csv")
MU1_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU1_sim3_G120.csv")
MU2_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU2_sim3_G120.csv")
V_M_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/v_M_sim3_G120.csv")
elapsed_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/elapsed_sim3_G120.csv")
#########################################################################################################################################
P_sim3_G120<- P_sim3_G120[,-1]
Phi_sim3_G120<- Phi_sim3_G120[,-1]
overdisp_sim3_G120<- overdisp_sim3_G120[,-1]
size_sim3_G120<- size_sim3_G120[,-1]
MU1_sim3_G120<- MU1_sim3_G120[,-1]
MU2_sim3_G120<- MU2_sim3_G120[,-1]
V_M_sim3_G120<- V_M_sim3_G120[,-1]
elapsed_sim3_G120<- elapsed_sim3_G120[,-1]
#############################################################################################################################################


############################################################################################################################################
P_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/P_sim4_G600.csv")
Phi_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/Phi_sim4_G600.csv")
overdisp_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/overdisp_sim4_G600.csv")
size_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/size_sim4_G600.csv")
MU1_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU1_sim4_G600.csv")
MU2_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU2_sim4_G600.csv")
V_M_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/v_M_sim4_G600.csv")
elapsed_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/elapsed_sim4_G600.csv")
#########################################################################################################################################
P_sim4_G600<- P_sim4_G600[,-1]
Phi_sim4_G600<- Phi_sim4_G600[,-1]
overdisp_sim4_G600<- overdisp_sim4_G600[,-1]
size_sim4_G600<- size_sim4_G600[,-1]
MU1_sim4_G600<- MU1_sim4_G600[,-1]
MU2_sim4_G600<- MU2_sim4_G600[,-1]
V_M_sim4_G600<- V_M_sim4_G600[,-1]
elapsed_sim4_G600<- elapsed_sim4_G600[,-1]
#############################################################################################################################################
##############################################################################################################################################

############################################################################################################################################
P_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/P_sim5_G1500.csv")
Phi_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/Phi_sim5_G1500.csv")
overdisp_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/overdisp_sim5_G1500.csv")
size_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/size_sim5_G1500.csv")
MU1_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU1_sim5_G1500.csv")
MU2_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/MU2_sim5_G1500.csv")
V_M_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/v_M_sim5_G1500.csv")
elapsed_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario3/elapsed_sim5_G1500.csv")
#########################################################################################################################################
P_sim5_G1500<- P_sim5_G1500[,-1]
Phi_sim5_G1500<- Phi_sim5_G1500[,-1]
overdisp_sim5_G1500<- overdisp_sim5_G1500[,-1]
size_sim5_G1500<- size_sim5_G1500[,-1]
MU1_sim5_G1500<- MU1_sim5_G1500[,-1]
MU2_sim5_G1500<- MU2_sim5_G1500[,-1]
V_M_sim5_G1500<- V_M_sim5_G1500[,-1]
elapsed_sim5_G1500<- elapsed_sim5_G1500[,-1]
#############################################################################################################################################
##############################################################################################################################################
### PLOTS###
###Pi###
par(mfrow=c(2,2))

boxplot(P_sim1_G12[,1],P_sim2_G60[,1],P_sim3_G120[,1],P_sim4_G600[,1],P_sim5_G1500[,1],main=expression(pi[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.5,col="Red",lty=3)

boxplot(P_sim1_G12[,2],P_sim2_G60[,2],P_sim3_G120[,2],P_sim4_G600[,2],P_sim5_G1500[,2],main=expression(pi[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.5,col="Red",lty=3)
##############################################################################################################################################
###Phi###
#par(mfrow=c(1,2))
boxplot(Phi_sim1_G12[,1],Phi_sim2_G60[,1],Phi_sim3_G120[,1],Phi_sim4_G600[,1],Phi_sim5_G1500[,1],main=expression(phi[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.1,col="Red",lty=3)

boxplot(Phi_sim1_G12[,2],Phi_sim2_G60[,2],Phi_sim3_G120[,2],Phi_sim4_G600[,2],Phi_sim5_G1500[,2],main=expression(phi[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=0.1,col="Red",lty=3)

##############################################################################################################################################
###V_means###
boxplot(V_M_sim1_G12, V_M_sim2_G60, V_M_sim3_G120, V_M_sim4_G600,main="V-Measures",xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=1,col="Red",lty=3)

##############################################################################################################################################
###size###
par(mfrow=c(2,2))
boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],size_sim5_G1500[,1],main=expression(nu[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=10,col="Red",lty=3)

boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],size_sim5_G1500[,2],main=expression(nu[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=100,col="Red",lty=3)

boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],size_sim5_G1500[,1],main=expression(nu[1]),outline = FALSE,xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=10,col="Red",lty=3)

boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],size_sim5_G1500[,2],main=expression(nu[2]),outline = FALSE,xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
abline(h=100,col="Red",lty=3)
##############################################################################################################################################################
###overdispersion###
# par(mfrow=c(1,2))
# boxplot(overdisp_sim1_G12[,1],overdisp_sim2_G60[,1],overdisp_sim3_G120[,1],overdisp_sim4_G600[,1],main=expression(alpha[1]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
# abline(h=1/5,col="Red",lty=3)
# 
# boxplot(overdisp_sim1_G12[,2],overdisp_sim2_G60[,2],overdisp_sim3_G120[,2],overdisp_sim4_G600[,2],main=expression(alpha[2]),xlab="G",names=c(12,60,120,600),cex.axis=0.7,ylim=c(0.095,0.15))
# abline(h=1/10,col="Red",lty=3)
# ###############################################################################################################################################
# ### Compute time###
# boxplot(elapsed_sim1_G12,elapsed_sim2_G60,elapsed_sim3_G120,elapsed_sim4_G600,main="Compute_time",xlab="G",names=c(12,60,120,600),cex.axis=0.7)

##############################################################################################################################################
# ### Tables###
# ### Pi###
# k<- c(rep(1,4),rep(2,4))
# A<- rep(c(12,60,120,600),2)
# B<- c(mean(P_sim1_G12[,1]),mean(P_sim2_G60[,1]),mean(P_sim3_G120[,1]),mean(P_sim4_G600[,1]),mean(P_sim5_G1500[,1])) 
# C<- c(sd(P_sim1_G12[,1]),sd(P_sim2_G60[,1]),sd(P_sim3_G120[,1]),sd(P_sim4_G600[,1])) 
# D<- c(mean(P_sim1_G12[,2]),mean(P_sim2_G60[,2]),mean(P_sim3_G120[,2]),mean(P_sim4_G600[,2]),mean(P_sim5_G1500[,2])) 
# E<- c(sd(P_sim1_G12[,2]),sd(P_sim2_G60[,2]),sd(P_sim3_G120[,2]),sd(P_sim4_G600[,2])) 
# 
# tab_P<- rbind(cbind(B,C),cbind(D,E))
# tab_P1<- cbind(k,A,tab_P)
# 
# colnames(tab_P1)<- c("k","G","Mean","SE")
# tab_P1
# ##############################################################################################################################################
# ### Phi###
# kk<- c(rep(1,4),rep(2,4))
# AA<- rep(c(12,60,120,600),2)
# BB<- c(mean(Phi_sim1_G12[,1]),mean(Phi_sim2_G60[,1]),mean(Phi_sim3_G120[,1]),mean(Phi_sim4_G600[,1])) 
# CC<- c(sd(Phi_sim1_G12[,1]),sd(Phi_sim2_G60[,1]),sd(Phi_sim3_G120[,1]),sd(Phi_sim4_G600[,1])) 
# DD<- c(mean(Phi_sim1_G12[,2]),mean(Phi_sim2_G60[,2]),mean(Phi_sim3_G120[,2]),mean(Phi_sim4_G600[,2])) 
# EE<- c(sd(Phi_sim1_G12[,2]),sd(Phi_sim2_G60[,2]),sd(Phi_sim3_G120[,2]),sd(Phi_sim4_G600[,2])) 
# 
# tab_Phi<- rbind(cbind(BB,CC),cbind(DD,EE))
# tab_Phi1<- cbind(kk,AA,tab_Phi)
# 
# colnames(tab_Phi1)<- c("k","G","Mean","SE")
# tab_Phi1
# 
# ##############################################################################################################################################
# xtable::xtable(tab_P1,digits = 5)
# xtable::xtable(tab_Phi1,digits = 5)
################################################################################################################################################
### MU###
mu_k1<- c(1,mean(MU1_sim1_G12),mean(MU1_sim2_G60),mean(MU1_sim3_G120),mean(MU1_sim4_G600),mean(MU1_sim5_G1500))
mu_k2<- c(2,mean(MU2_sim1_G12),mean(MU2_sim2_G60),mean(MU2_sim3_G120),mean(MU2_sim4_G600),mean(MU2_sim5_G1500))
#mu_k1
#mu_k2
#k<- c(1,2)
tab_mu<- rbind(mu_k1,mu_k2)
colnames(tab_mu)<- c("G",12,60,120,600,1500)
print(tab_mu)
# xtable::xtable(tab_mu,digits = 5)
###########################################################################################################################################
# ### Computeing time###
# k<- c(12,60,120,600)
# M<- c(mean(elapsed_sim1_G12),mean(elapsed_sim2_G60),mean(elapsed_sim3_G120),mean(elapsed_sim4_G600))
# S<- c(sd(elapsed_sim1_G12),sd(elapsed_sim2_G60),sd(elapsed_sim3_G120),sd(elapsed_sim4_G600))
# tab_compute<- cbind(k,M,S)
# colnames(tab_compute)<- c("G","Mean","SE")
# tab_compute
# xtable::xtable(tab_compute)
# ##############################################################################################################################################
# ### Size###
# #mean((size_sim1_G12[,1]-5)^2)
# #mean((size_sim2_G60[,1]-5)^2)
# #mean((size_sim3_G120[,1]-5)^2)
# #mean((size_sim4_G600[,1]-5)^2)
# 
# size_k1<- c(1,mean(abs(size_sim1_G12[,1]-5)),mean(abs(size_sim2_G60[,1]-5)),mean(abs(size_sim3_G120[,1]-5)),mean(abs(size_sim4_G600[,1]-5)))
# 
# #mean((size_sim1_G12[,2]-10)^2)
# #mean((size_sim2_G60[,2]-10)^2)
# #mean((size_sim3_G120[,2]-10)^2)
# #mean((size_sim4_G600[,2]-10)^2)
# 
# size_k2<- c(2,mean(abs(size_sim1_G12[,2]-10)),mean(abs(size_sim2_G60[,2]-10)),mean(abs(size_sim3_G120[,2]-10)),mean(abs(size_sim4_G600[,2]-10)))
# 
# tab_size<- rbind(size_k1,size_k2)
# colnames(tab_size)<- c("k",12,60,120,600)
# tab_size
# xtable::xtable(tab_size,digits = 6)
# ########################################################################################################################
# ### Overdispersion###
# 
# mean(abs(overdisp_sim1_G12[,1]-5))
# mean(abs(overdisp_sim2_G60[,1]-5))
# mean(abs(overdisp_sim3_G120[,1]-5))
# mean(abs(overdisp_sim4_G600[,1]-5))
# 
# #mean((size_sim1_G12[,2]-10)^2)
# #mean((size_sim2_G60[,2]-10)^2)
# #mean((size_sim3_G120[,2]-10)^2)
# #mean((size_sim4_G600[,2]-10)^2)
# 
# 
# mean(abs(overdisp_sim1_G12[,2]-10))
# mean(abs(overdisp_sim2_G60[,2]-10))
# mean(abs(overdisp_sim3_G120[,2]-10))
# mean(abs(overdisp_sim4_G600[,2]-10))
# 

```





## Scenario 4: Size(5,20), Function: glm.nb

```{r Sc4,eval=TRUE,echo=FALSE}

############################################################################################################################################
P_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/P_sim1_G12.csv")
Phi_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/Phi_sim1_G12.csv")
overdisp_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/overdisp_sim1_G12.csv")
size_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/size_sim1_G12.csv")
MU1_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU1_sim1_G12.csv")
MU2_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU2_sim1_G12.csv")
V_M_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/v_M_sim1_G12.csv")
elapsed_sim1_G12<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/elapsed_sim1_G12.csv")
#########################################################################################################################################
P_sim1_G12<- P_sim1_G12[,-1]
Phi_sim1_G12<- Phi_sim1_G12[,-1]
overdisp_sim1_G12<- overdisp_sim1_G12[,-1]
size_sim1_G12<- size_sim1_G12[,-1]
MU1_sim1_G12<- MU1_sim1_G12[,-1]
MU2_sim1_G12<- MU2_sim1_G12[,-1]
V_M_sim1_G12<- V_M_sim1_G12[,-1]
elapsed_sim1_G12<- elapsed_sim1_G12[,-1]
#############################################################################################################################################

P_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/P_sim2_G60.csv")
Phi_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/Phi_sim2_G60.csv")
overdisp_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/overdisp_sim2_G60.csv")
size_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/size_sim2_G60.csv")
MU1_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU1_sim2_G60.csv")
MU2_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU2_sim2_G60.csv")
V_M_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/v_M_sim2_G60.csv")
elapsed_sim2_G60<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/elapsed_sim2_G60.csv")
#########################################################################################################################################
P_sim2_G60<- P_sim2_G60[,-1]
Phi_sim2_G60<- Phi_sim2_G60[,-1]
overdisp_sim2_G60<- overdisp_sim2_G60[,-1]
size_sim2_G60<- size_sim2_G60[,-1]
MU1_sim2_G60<- MU1_sim2_G60[,-1]
MU2_sim2_G60<- MU2_sim2_G60[,-1]
V_M_sim2_G60<- V_M_sim2_G60[,-1]
elapsed_sim2_G60<- elapsed_sim2_G60[,-1]
#############################################################################################################################################
P_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/P_sim3_G120.csv")
Phi_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/Phi_sim3_G120.csv")
overdisp_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/overdisp_sim3_G120.csv")
size_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/size_sim3_G120.csv")
MU1_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU1_sim3_G120.csv")
MU2_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU2_sim3_G120.csv")
V_M_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/v_M_sim3_G120.csv")
elapsed_sim3_G120<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/elapsed_sim3_G120.csv")
#########################################################################################################################################
P_sim3_G120<- P_sim3_G120[,-1]
Phi_sim3_G120<- Phi_sim3_G120[,-1]
overdisp_sim3_G120<- overdisp_sim3_G120[,-1]
size_sim3_G120<- size_sim3_G120[,-1]
MU1_sim3_G120<- MU1_sim3_G120[,-1]
MU2_sim3_G120<- MU2_sim3_G120[,-1]
V_M_sim3_G120<- V_M_sim3_G120[,-1]
elapsed_sim3_G120<- elapsed_sim3_G120[,-1]
#############################################################################################################################################


############################################################################################################################################
P_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/P_sim4_G600.csv")
Phi_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/Phi_sim4_G600.csv")
overdisp_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/overdisp_sim4_G600.csv")
size_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/size_sim4_G600.csv")
MU1_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU1_sim4_G600.csv")
MU2_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU2_sim4_G600.csv")
V_M_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/v_M_sim4_G600.csv")
elapsed_sim4_G600<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/elapsed_sim4_G600.csv")
#########################################################################################################################################
P_sim4_G600<- P_sim4_G600[,-1]
Phi_sim4_G600<- Phi_sim4_G600[,-1]
overdisp_sim4_G600<- overdisp_sim4_G600[,-1]
size_sim4_G600<- size_sim4_G600[,-1]
MU1_sim4_G600<- MU1_sim4_G600[,-1]
MU2_sim4_G600<- MU2_sim4_G600[,-1]
V_M_sim4_G600<- V_M_sim4_G600[,-1]
elapsed_sim4_G600<- elapsed_sim4_G600[,-1]
#############################################################################################################################################
##############################################################################################################################################

############################################################################################################################################
# P_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/P_sim5_G1500.csv")
# Phi_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/Phi_sim5_G1500.csv")
# overdisp_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/overdisp_sim5_G1500.csv")
# size_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/size_sim5_G1500.csv")
# MU1_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU1_sim5_G1500.csv")
# MU2_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/MU2_sim5_G1500.csv")
# V_M_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/v_M_sim5_G1500.csv")
# elapsed_sim5_G1500<- read.csv("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario4/elapsed_sim5_G1500.csv")
# #########################################################################################################################################
# P_sim5_G1500<- P_sim5_G1500[,-1]
# Phi_sim5_G1500<- Phi_sim5_G1500[,-1]
# overdisp_sim5_G1500<- overdisp_sim5_G1500[,-1]
# size_sim5_G1500<- size_sim5_G1500[,-1]
# MU1_sim5_G1500<- MU1_sim5_G1500[,-1]
# MU2_sim5_G1500<- MU2_sim5_G1500[,-1]
# V_M_sim5_G1500<- V_M_sim5_G1500[,-1]
# elapsed_sim5_G1500<- elapsed_sim5_G1500[,-1]
#############################################################################################################################################
##############################################################################################################################################
### PLOTS###
###Pi###
par(mfrow=c(2,2))

boxplot(P_sim1_G12[,1],P_sim2_G60[,1],P_sim3_G120[,1],P_sim4_G600[,1],main=expression(pi[1]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=0.5,col="Red",lty=3)

boxplot(P_sim1_G12[,2],P_sim2_G60[,2],P_sim3_G120[,2],P_sim4_G600[,2],main=expression(pi[2]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=0.5,col="Red",lty=3)




# par(mfrow=c(2,2))
# 
# boxplot(P_sim1_G12[,1],P_sim2_G60[,1],P_sim3_G120[,1],P_sim4_G600[,1],P_sim5_G1500[,1],main=expression(pi[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
# abline(h=0.5,col="Red",lty=3)
# 
# boxplot(P_sim1_G12[,2],P_sim2_G60[,2],P_sim3_G120[,2],P_sim4_G600[,2],P_sim5_G1500[,2],main=expression(pi[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
# abline(h=0.5,col="Red",lty=3)
##############################################################################################################################################
###Phi###
boxplot(Phi_sim1_G12[,1],Phi_sim2_G60[,1],Phi_sim3_G120[,1],Phi_sim4_G600[,1],main=expression(phi[1]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=0.1,col="Red",lty=3)

boxplot(Phi_sim1_G12[,2],Phi_sim2_G60[,2],Phi_sim3_G120[,2],Phi_sim4_G600[,2],main=expression(phi[2]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=0.1,col="Red",lty=3)


# 
# boxplot(Phi_sim1_G12[,1],Phi_sim2_G60[,1],Phi_sim3_G120[,1],Phi_sim4_G600[,1],Phi_sim5_G1500[,1],main=expression(phi[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
# abline(h=0.1,col="Red",lty=3)
# 
# boxplot(Phi_sim1_G12[,2],Phi_sim2_G60[,2],Phi_sim3_G120[,2],Phi_sim4_G600[,2],Phi_sim5_G1500[,2],main=expression(phi[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
# abline(h=0.1,col="Red",lty=3)

##############################################################################################################################################
###V_means###
boxplot(V_M_sim1_G12, V_M_sim2_G60, V_M_sim3_G120, V_M_sim4_G600,main="V-Measures",xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=1,col="Red",lty=3)

# boxplot(V_M_sim1_G12, V_M_sim2_G60, V_M_sim3_G120, V_M_sim4_G600,main="V-Measures",xlab="G",names=c(12,60,120,600),cex.axis=0.7)
# abline(h=1,col="Red",lty=3)

##############################################################################################################################################
###size###

par(mfrow=c(2,2))
boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],main=expression(nu[1]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=5,col="Red",lty=3)

boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],main=expression(nu[2]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=20,col="Red",lty=3)

boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],main=expression(nu[1]),outline = FALSE,xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=5,col="Red",lty=3)

boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],main=expression(nu[2]),outline = FALSE,xlab="G",names=c(12,60,120,600),cex.axis=0.7)
abline(h=20,col="Red",lty=3)


# par(mfrow=c(2,2))
# boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],size_sim5_G1500[,1],main=expression(nu[1]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
# abline(h=5,col="Red",lty=3)
# 
# boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],size_sim5_G1500[,2],main=expression(nu[2]),xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
# abline(h=20,col="Red",lty=3)
# 
# boxplot(size_sim1_G12[,1],size_sim2_G60[,1],size_sim3_G120[,1],size_sim4_G600[,1],size_sim5_G1500[,1],main=expression(nu[1]),outline = FALSE,xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
# abline(h=5,col="Red",lty=3)
# 
# boxplot(size_sim1_G12[,2],size_sim2_G60[,2],size_sim3_G120[,2],size_sim4_G600[,2],size_sim5_G1500[,2],main=expression(nu[2]),outline = FALSE,xlab="G",names=c(12,60,120,600,1500),cex.axis=0.7)
# abline(h=20,col="Red",lty=3)
##############################################################################################################################################################
###overdispersion###
# par(mfrow=c(1,2))
# boxplot(overdisp_sim1_G12[,1],overdisp_sim2_G60[,1],overdisp_sim3_G120[,1],overdisp_sim4_G600[,1],main=expression(alpha[1]),xlab="G",names=c(12,60,120,600),cex.axis=0.7)
# abline(h=1/5,col="Red",lty=3)
# 
# boxplot(overdisp_sim1_G12[,2],overdisp_sim2_G60[,2],overdisp_sim3_G120[,2],overdisp_sim4_G600[,2],main=expression(alpha[2]),xlab="G",names=c(12,60,120,600),cex.axis=0.7,ylim=c(0.095,0.15))
# abline(h=1/10,col="Red",lty=3)
# ###############################################################################################################################################
# ### Compute time###
# boxplot(elapsed_sim1_G12,elapsed_sim2_G60,elapsed_sim3_G120,elapsed_sim4_G600,main="Compute_time",xlab="G",names=c(12,60,120,600),cex.axis=0.7)

##############################################################################################################################################
# ### Tables###
# ### Pi###
# k<- c(rep(1,4),rep(2,4))
# A<- rep(c(12,60,120,600),2)
# B<- c(mean(P_sim1_G12[,1]),mean(P_sim2_G60[,1]),mean(P_sim3_G120[,1]),mean(P_sim4_G600[,1]),mean(P_sim5_G1500[,1])) 
# C<- c(sd(P_sim1_G12[,1]),sd(P_sim2_G60[,1]),sd(P_sim3_G120[,1]),sd(P_sim4_G600[,1])) 
# D<- c(mean(P_sim1_G12[,2]),mean(P_sim2_G60[,2]),mean(P_sim3_G120[,2]),mean(P_sim4_G600[,2]),mean(P_sim5_G1500[,2])) 
# E<- c(sd(P_sim1_G12[,2]),sd(P_sim2_G60[,2]),sd(P_sim3_G120[,2]),sd(P_sim4_G600[,2])) 
# 
# tab_P<- rbind(cbind(B,C),cbind(D,E))
# tab_P1<- cbind(k,A,tab_P)
# 
# colnames(tab_P1)<- c("k","G","Mean","SE")
# tab_P1
# ##############################################################################################################################################
# ### Phi###
# kk<- c(rep(1,4),rep(2,4))
# AA<- rep(c(12,60,120,600),2)
# BB<- c(mean(Phi_sim1_G12[,1]),mean(Phi_sim2_G60[,1]),mean(Phi_sim3_G120[,1]),mean(Phi_sim4_G600[,1])) 
# CC<- c(sd(Phi_sim1_G12[,1]),sd(Phi_sim2_G60[,1]),sd(Phi_sim3_G120[,1]),sd(Phi_sim4_G600[,1])) 
# DD<- c(mean(Phi_sim1_G12[,2]),mean(Phi_sim2_G60[,2]),mean(Phi_sim3_G120[,2]),mean(Phi_sim4_G600[,2])) 
# EE<- c(sd(Phi_sim1_G12[,2]),sd(Phi_sim2_G60[,2]),sd(Phi_sim3_G120[,2]),sd(Phi_sim4_G600[,2])) 
# 
# tab_Phi<- rbind(cbind(BB,CC),cbind(DD,EE))
# tab_Phi1<- cbind(kk,AA,tab_Phi)
# 
# colnames(tab_Phi1)<- c("k","G","Mean","SE")
# tab_Phi1
# 
# ##############################################################################################################################################
# xtable::xtable(tab_P1,digits = 5)
# xtable::xtable(tab_Phi1,digits = 5)
################################################################################################################################################
### MU###
mu_k1<- c(1,mean(MU1_sim1_G12),mean(MU1_sim2_G60),mean(MU1_sim3_G120),mean(MU1_sim4_G600))
mu_k2<- c(2,mean(MU2_sim1_G12),mean(MU2_sim2_G60),mean(MU2_sim3_G120),mean(MU2_sim4_G600))
tab_mu<- rbind(mu_k1,mu_k2)
colnames(tab_mu)<- c("G",12,60,120,600)
print(tab_mu)


# 
# mu_k1<- c(1,mean(MU1_sim1_G12),mean(MU1_sim2_G60),mean(MU1_sim3_G120),mean(MU1_sim4_G600),mean(MU1_sim5_G1500))
# mu_k2<- c(2,mean(MU2_sim1_G12),mean(MU2_sim2_G60),mean(MU2_sim3_G120),mean(MU2_sim4_G600),mean(MU2_sim5_G1500))
#mu_k1
#mu_k2
#k<- c(1,2)
# tab_mu<- rbind(mu_k1,mu_k2)
# colnames(tab_mu)<- c("G",12,60,120,600,1500)
# print(tab_mu)
# xtable::xtable(tab_mu,digits = 5)
###########################################################################################################################################
# ### Computeing time###
# k<- c(12,60,120,600)
# M<- c(mean(elapsed_sim1_G12),mean(elapsed_sim2_G60),mean(elapsed_sim3_G120),mean(elapsed_sim4_G600))
# S<- c(sd(elapsed_sim1_G12),sd(elapsed_sim2_G60),sd(elapsed_sim3_G120),sd(elapsed_sim4_G600))
# tab_compute<- cbind(k,M,S)
# colnames(tab_compute)<- c("G","Mean","SE")
# tab_compute
# xtable::xtable(tab_compute)
# ##############################################################################################################################################
# ### Size###
# #mean((size_sim1_G12[,1]-5)^2)
# #mean((size_sim2_G60[,1]-5)^2)
# #mean((size_sim3_G120[,1]-5)^2)
# #mean((size_sim4_G600[,1]-5)^2)
# 
# size_k1<- c(1,mean(abs(size_sim1_G12[,1]-5)),mean(abs(size_sim2_G60[,1]-5)),mean(abs(size_sim3_G120[,1]-5)),mean(abs(size_sim4_G600[,1]-5)))
# 
# #mean((size_sim1_G12[,2]-10)^2)
# #mean((size_sim2_G60[,2]-10)^2)
# #mean((size_sim3_G120[,2]-10)^2)
# #mean((size_sim4_G600[,2]-10)^2)
# 
# size_k2<- c(2,mean(abs(size_sim1_G12[,2]-10)),mean(abs(size_sim2_G60[,2]-10)),mean(abs(size_sim3_G120[,2]-10)),mean(abs(size_sim4_G600[,2]-10)))
# 
# tab_size<- rbind(size_k1,size_k2)
# colnames(tab_size)<- c("k",12,60,120,600)
# tab_size
# xtable::xtable(tab_size,digits = 6)
# ########################################################################################################################
# ### Overdispersion###
# 
# mean(abs(overdisp_sim1_G12[,1]-5))
# mean(abs(overdisp_sim2_G60[,1]-5))
# mean(abs(overdisp_sim3_G120[,1]-5))
# mean(abs(overdisp_sim4_G600[,1]-5))
# 
# #mean((size_sim1_G12[,2]-10)^2)
# #mean((size_sim2_G60[,2]-10)^2)
# #mean((size_sim3_G120[,2]-10)^2)
# #mean((size_sim4_G600[,2]-10)^2)
# 
# 
# mean(abs(overdisp_sim1_G12[,2]-10))
# mean(abs(overdisp_sim2_G60[,2]-10))
# mean(abs(overdisp_sim3_G120[,2]-10))
# mean(abs(overdisp_sim4_G600[,2]-10))
# 

```