---
title: "ZINB_Modify_March2023"
author: "Zahra"
date: "2023-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(xtable)
library(MASS)
library(FDRSeg)


```


``` {r Scenario1-sim1,eval=TRUE,echo=FALSE}
rm(list = ls())

###################################################################################################
### Generate data from Zero-inflated Negative Binomial Distribution### 
source("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Cases/ZINB_March2023.R")
#source("path/to/some/file.R")
#source(Fix_all_update_nu.R)
###################################################################################################
###################################################################################################
### Data sim_1###
### Generate Y Matrix_Matrix of raw counts###
### case_1###
set.seed(111)
N<- 60
G<- 120
P<- c(0.5,0.5)
Phi<- c(0.1,0.1)
K<- length(P)
#size<- c(10,5)
#size<- c(5,10)
size<- c(5,20)

#P<- c(0.25,0.25,0.25,0.25)
#N<- 1000
#G<- 10
#Phi<- c(0.1,0.1,0.2,0.2)
#P<- c(0.25,0.25,0.25,0.25)
#P1<- c(0.4,0.3,0.2,0.1)


#mu_1<- rgamma(n=G,shape=10,scale=1/2)
#mu_2<- rgamma(n=G,shape=10,scale=1/1.5)


#mu_1<- c(rep(5,(G/2)),rep(10,G/2))
#mu_2<- c(rep(10,(G/2)),rep(5,G/2))

mu_1<- c(rep(5,G))
mu_2<- c(rep(10,G))

MU<- rbind(mu_1,mu_2)
#MU

#S<- 256
#S<- 128
S<- 100
#S<- 3
P_hat<- matrix(NA,ncol=length(P),nrow=S)
#P_hat<- NULL
Phi_hat<- matrix(NA,ncol=length(P),nrow=S)
overdisp_hat<- matrix(NA,nrow=S,ncol=K)
size_hat<- matrix(NA,nrow=S,ncol=K)

#Phi_hat
#phi_hat2<- NULL
mu1_hat<- matrix(NA,ncol = G,nrow=S)
mu2_hat<- matrix(NA,ncol = G,nrow=S)
#lambda3_hat<- matrix(NA,ncol = G,nrow=S)
#lambda4_hat<- matrix(NA,ncol = G,nrow=S)

#MU_1<- MU_2<- matrix(NA,nrow=S,ncol=G)
V_M<- rep(NA,S)
elapsed<- rep(NA,S)

for(s in 1:S){
  
  # mu_1<- rgamma(n=G,shape=10,scale=1/2)
  
  
  #mu_2<- rgamma(n=G,shape=10,scale=1/0.2)
  
  #MU<- rbind(mu_1,mu_2)
  
  
  
  #for(s in 1:S){
  
  
  #for(iteration in 1:r){
  
  #p_hat<- NULL
  #phi_hat1<- NULL
  #phi_hat2<- NULL
  #lambda1_hat<- matrix(0,ncol = G,nrow=r)
  #lambda2_hat<- matrix(0,ncol = G,nrow=r)
  
  #for(iter in 1:r){
  #clust<- rbinom(size=1,n=N,p=0.5)
  clust<- sample(1:2,size=N,replace = TRUE,prob=P)
  #clust
  #length(clust[clust==1])
  
  
  #clust<- sample(c(1,2),size=N,replace = TRUE,prob=pn) 
  #clust
  
  
  cell_matrix<- U_ng<-  matrix(rep(0,N*G),nrow=N,ncol=G)
  
  for(n in 1:N){
    for(g in 1:G){
      if(clust[n]==1) {
        out_1 = ZINB_r_U(n=1,prob=Phi[1],theta=MU[1,g],disp_param=size[1])
        cell_matrix[n,g]<- out_1$Y
        U_ng[n,g]<- out_1$U}
      
      else if(clust[n]==2){
        out_2 = ZINB_r_U(n=1,prob=Phi[2],theta=MU[2,g],disp_param=size[2])
        cell_matrix[n,g]<- out_2$Y
        U_ng[n,g]<- out_2$U}
        
    }
  }
  
  

  
  #result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)
  elapsed[s]<- system.time({result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)})["elapsed"]
  P_hat[s,]<- result_test$P
  Phi_hat[s,]<- result_test$Phi
  mu1_hat[s,]<- result_test$MU[1,]
  mu2_hat[s,]<- result_test$MU[2,]
  overdisp_hat[s,]<- result_test$a_hat
  size_hat[s,]<- result_test$size_est
   Z0<- clust
   zhat<- result_test$postprobs
   zhat<- apply(zhat,1,which.max)
   V_M[s]<- v_measure(Z0,zhat)
  
  
 
}



###############################################################
L1<- cbind(colMeans(mu1_hat),mu_1)
colnames(L1)<- c("mu1_hat","mu1")
#print(L1)
L2<- cbind(colMeans(mu2_hat),mu_2)
colnames(L2)<- c("mu2_hat","mu2")
#print(L2)


dif_mu1<- dif_mu2<- matrix(NA,nrow=S,ncol=G)
#mad_mu1<- mad_mu2<- matrix(NA,nrow=S,ncol=G)

for(s in 1:S){
  dif_mu1[s,]<- (mu1_hat[s,]-mu_1)^2
  dif_mu2[s,]<- (mu2_hat[s,]-mu_2)^2
 # mad_mu1[s,]<- median(abs(mu1_hat-mu_1))
  #mad_mu2[s,]<- median(abs(mu2_hat-mu_2))
  
}

#dif_mu1
#dif_mu2

MSE_mu1<- apply(dif_mu1,2,mean)
#MSE_mu1
#mean(MSE_mu1)

MSE_mu2<- apply(dif_mu2,2,mean)

#MSE_mu2
MSE_MU<- rbind(mean(MSE_mu1),mean(MSE_mu2))
#MSE_MU
#xtable(MSE_MU)
#mean(MSE_mu1)

#########################################################################################


P_sim1_n60<- write.csv(P_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim1_n60.csv")
Phi_sim1_n60<- write.csv( Phi_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/Phi_sim1_n60.csv")
overdisp_sim1_n60<- write.csv(overdisp_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim1_n60.csv")
size_sim1_n60<- write.csv(size_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim1_n60.csv")
MU1_sim1_n60<- write.csv(MSE_mu1,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim1_n60.csv")
MU2_sim1_n60<- write.csv(MSE_mu2,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim1_n60.csv")
V_M_sim1_n60<- write.csv(V_M,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim1_n60.csv")
elapsed_sim1_n60<- write.csv(elapsed,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim1_n60.csv")


```



``` {r Scenario1-sim2,eval=TRUE,echo=FALSE}
rm(list = ls())
source("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Cases/ZINB_March2023.R")


###################################################################################################

###################################################################################################
###################################################################################################
### Data sim_2###
### Generate Y Matrix_Matrix of raw counts###
### case_1###
set.seed(222)
N<- 120
G<- 120
P<- c(0.5,0.5)
Phi<- c(0.1,0.1)
K<- length(P)
#size<- c(10,5)
#size<- c(5,10)
size<- c(5,20)

#P<- c(0.25,0.25,0.25,0.25)
#N<- 1000
#G<- 10
#Phi<- c(0.1,0.1,0.2,0.2)
#P<- c(0.25,0.25,0.25,0.25)
#P1<- c(0.4,0.3,0.2,0.1)


#mu_1<- rgamma(n=G,shape=10,scale=1/2)
#mu_2<- rgamma(n=G,shape=10,scale=1/1.5)


#mu_1<- c(rep(5,(G/2)),rep(10,G/2))
#mu_2<- c(rep(10,(G/2)),rep(5,G/2))

mu_1<- c(rep(5,G))
mu_2<- c(rep(10,G))
MU<- rbind(mu_1,mu_2)
#MU

#S<- 256
#S<- 128
S<- 100
#S<- 3
P_hat<- matrix(NA,ncol=length(P),nrow=S)
#P_hat<- NULL
Phi_hat<- matrix(NA,ncol=length(P),nrow=S)
overdisp_hat<- matrix(NA,nrow=S,ncol=K)
size_hat<- matrix(NA,nrow=S,ncol=K)

#Phi_hat
#phi_hat2<- NULL
mu1_hat<- matrix(NA,ncol = G,nrow=S)
mu2_hat<- matrix(NA,ncol = G,nrow=S)
#lambda3_hat<- matrix(NA,ncol = G,nrow=S)
#lambda4_hat<- matrix(NA,ncol = G,nrow=S)

#MU_1<- MU_2<- matrix(NA,nrow=S,ncol=G)
V_M<- rep(NA,S)
elapsed<- rep(NA,S)

for(s in 1:S){

  # mu_1<- rgamma(n=G,shape=10,scale=1/2)


  #mu_2<- rgamma(n=G,shape=10,scale=1/0.2)

  #MU<- rbind(mu_1,mu_2)



  #for(s in 1:S){


  #for(iteration in 1:r){

  #p_hat<- NULL
  #phi_hat1<- NULL
  #phi_hat2<- NULL
  #lambda1_hat<- matrix(0,ncol = G,nrow=r)
  #lambda2_hat<- matrix(0,ncol = G,nrow=r)

  #for(iter in 1:r){
  #clust<- rbinom(size=1,n=N,p=0.5)
  clust<- sample(1:2,size=N,replace = TRUE,prob=P)
  #clust
  #length(clust[clust==1])


  #clust<- sample(c(1,2),size=N,replace = TRUE,prob=pn)
  #clust


  cell_matrix<- U_ng<-  matrix(rep(0,N*G),nrow=N,ncol=G)

  for(n in 1:N){
    for(g in 1:G){
      if(clust[n]==1) {
        out_1 = ZINB_r_U(n=1,prob=Phi[1],theta=MU[1,g],disp_param=size[1])
        cell_matrix[n,g]<- out_1$Y
        U_ng[n,g]<- out_1$U}

      else if(clust[n]==2){
        out_2 = ZINB_r_U(n=1,prob=Phi[2],theta=MU[2,g],disp_param=size[2])
        cell_matrix[n,g]<- out_2$Y
        U_ng[n,g]<- out_2$U}

    }
  }








#cell_matrix
  #cell_matrix

  #plot(hclust(dist(cell_matrix)))


  #cell_matrix
  #dim(cell_matrix)


  #result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)
  elapsed[s]<- system.time({result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)})["elapsed"]
  P_hat[s,]<- result_test$P
  Phi_hat[s,]<- result_test$Phi
  mu1_hat[s,]<- result_test$MU[1,]
  mu2_hat[s,]<- result_test$MU[2,]
  overdisp_hat[s,]<- result_test$a_hat
  size_hat[s,]<- result_test$size_est
   Z0<- clust
   zhat<- result_test$postprobs
   zhat<- apply(zhat,1,which.max)
   V_M[s]<- v_measure(Z0,zhat)
  #


}



###############################################################
L1<- cbind(colMeans(mu1_hat),mu_1)
colnames(L1)<- c("mu1_hat","mu1")
#print(L1)
L2<- cbind(colMeans(mu2_hat),mu_2)
colnames(L2)<- c("mu2_hat","mu2")
#print(L2)

dif_mu1<- dif_mu2<- matrix(NA,nrow=S,ncol=G)

for(s in 1:S){
  dif_mu1[s,]<- (mu1_hat[s,]-mu_1)^2
  dif_mu2[s,]<- (mu2_hat[s,]-mu_2)^2

}

#dif_mu1
#dif_mu2

MSE_mu1<- apply(dif_mu1,2,mean)
#MSE_mu1
#mean(MSE_mu1)

MSE_mu2<- apply(dif_mu2,2,mean)
#MSE_mu2
#mean(MSE_mu2)
#mu1_hat
#boxplot(mu1_hat)
#abline(h=5)
#abline(h=10)

#boxplot(mu2_hat)
#abline(h=5)
#abline(h=10)

#MSE_mu1
#MSE_mu2
MSE_MU<- rbind(mean(MSE_mu1),mean(MSE_mu2))
#MSE_MU
#xtable(MSE_MU)
#mean(MSE_mu1)

#########################################################################################


P_sim2_n120<- write.csv(P_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim2_n120.csv")
Phi_sim2_n120<- write.csv( Phi_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/Phi_sim2_n120.csv")
overdisp_sim2_n120<- write.csv(overdisp_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim2_n120.csv")
size_sim2_n120<- write.csv(size_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim2_n120.csv")
MU1_sim2_n120<- write.csv(MSE_mu1,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim2_n120.csv")
MU2_sim2_n120<- write.csv(MSE_mu2,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim2_n120.csv")
V_M_sim2_n120<- write.csv(V_M,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim2_n120.csv")
elapsed_sim2_n120<- write.csv(elapsed,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim2_n120.csv")


```






``` {r Scenario1-sim3,eval=TRUE,echo=FALSE}
rm(list = ls())
source("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Cases/ZINB_March2023.R")

###################################################################################################

###################################################################################################
###################################################################################################
### Data sim_3###
### Generate Y Matrix_Matrix of raw counts###
### case_1###
set.seed(333)
N<- 300
G<- 120
P<- c(0.5,0.5)
Phi<- c(0.1,0.1)
K<- length(P)
#size<- c(10,5)
#size<- c(5,10)
size<- c(5,20)

#P<- c(0.25,0.25,0.25,0.25)
#N<- 1000
#G<- 10
#Phi<- c(0.1,0.1,0.2,0.2)
#P<- c(0.25,0.25,0.25,0.25)
#P1<- c(0.4,0.3,0.2,0.1)


#mu_1<- rgamma(n=G,shape=10,scale=1/2)
#mu_2<- rgamma(n=G,shape=10,scale=1/1.5)


#mu_1<- c(rep(5,(G/2)),rep(10,G/2))
#mu_2<- c(rep(10,(G/2)),rep(5,G/2))

mu_1<- c(rep(5,G))
mu_2<- c(rep(10,G))

MU<- rbind(mu_1,mu_2)
#MU

#S<- 256
#S<- 128
S<- 100
#S<- 3
P_hat<- matrix(NA,ncol=length(P),nrow=S)
#P_hat<- NULL
Phi_hat<- matrix(NA,ncol=length(P),nrow=S)
overdisp_hat<- matrix(NA,nrow=S,ncol=K)
size_hat<- matrix(NA,nrow=S,ncol=K)

#Phi_hat
#phi_hat2<- NULL
mu1_hat<- matrix(NA,ncol = G,nrow=S)
mu2_hat<- matrix(NA,ncol = G,nrow=S)
#lambda3_hat<- matrix(NA,ncol = G,nrow=S)
#lambda4_hat<- matrix(NA,ncol = G,nrow=S)

#MU_1<- MU_2<- matrix(NA,nrow=S,ncol=G)
V_M<- rep(NA,S)
elapsed<- rep(NA,S)

for(s in 1:S){

  # mu_1<- rgamma(n=G,shape=10,scale=1/2)


  #mu_2<- rgamma(n=G,shape=10,scale=1/0.2)

  #MU<- rbind(mu_1,mu_2)



  #for(s in 1:S){


  #for(iteration in 1:r){

  #p_hat<- NULL
  #phi_hat1<- NULL
  #phi_hat2<- NULL
  #lambda1_hat<- matrix(0,ncol = G,nrow=r)
  #lambda2_hat<- matrix(0,ncol = G,nrow=r)

  #for(iter in 1:r){
  #clust<- rbinom(size=1,n=N,p=0.5)
  clust<- sample(1:2,size=N,replace = TRUE,prob=P)
  #clust
  #length(clust[clust==1])


  #clust<- sample(c(1,2),size=N,replace = TRUE,prob=pn)
  #clust


  cell_matrix<- U_ng<-  matrix(rep(0,N*G),nrow=N,ncol=G)

  for(n in 1:N){
    for(g in 1:G){
      if(clust[n]==1) {
        out_1 = ZINB_r_U(n=1,prob=Phi[1],theta=MU[1,g],disp_param=size[1])
        cell_matrix[n,g]<- out_1$Y
        U_ng[n,g]<- out_1$U}

      else if(clust[n]==2){
        out_2 = ZINB_r_U(n=1,prob=Phi[2],theta=MU[2,g],disp_param=size[2])
        cell_matrix[n,g]<- out_2$Y
        U_ng[n,g]<- out_2$U}

    }
  }





#cell_matrix
  #cell_matrix

  #plot(hclust(dist(cell_matrix)))


  #cell_matrix
  #dim(cell_matrix)


  #result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)
  elapsed[s]<- system.time({result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)})["elapsed"]
  P_hat[s,]<- result_test$P
  Phi_hat[s,]<- result_test$Phi
  mu1_hat[s,]<- result_test$MU[1,]
  mu2_hat[s,]<- result_test$MU[2,]
  overdisp_hat[s,]<- result_test$a_hat
  size_hat[s,]<- result_test$size_est
   Z0<- clust
   zhat<- result_test$postprobs
   zhat<- apply(zhat,1,which.max)
   V_M[s]<- v_measure(Z0,zhat)



}




###############################################################
L1<- cbind(colMeans(mu1_hat),mu_1)
colnames(L1)<- c("mu1_hat","mu1")
#print(L1)
L2<- cbind(colMeans(mu2_hat),mu_2)
colnames(L2)<- c("mu2_hat","mu2")
#print(L2)

dif_mu1<- dif_mu2<- matrix(NA,nrow=S,ncol=G)

for(s in 1:S){
  dif_mu1[s,]<- (mu1_hat[s,]-mu_1)^2
  dif_mu2[s,]<- (mu2_hat[s,]-mu_2)^2

}

#dif_mu1
#dif_mu2

MSE_mu1<- apply(dif_mu1,2,mean)
#MSE_mu1
#mean(MSE_mu1)

MSE_mu2<- apply(dif_mu2,2,mean)
#MSE_mu2
#mean(MSE_mu2)
#mu1_hat
#boxplot(mu1_hat)
#abline(h=5)
#abline(h=10)

#boxplot(mu2_hat)
#abline(h=5)
#abline(h=10)

#MSE_mu1
#MSE_mu2
MSE_MU<- rbind(mean(MSE_mu1),mean(MSE_mu2))
#MSE_MU
#xtable(MSE_MU)
#mean(MSE_mu1)

#########################################################################################

P_sim3_n300<- write.csv(P_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim3_n300.csv")
Phi_sim3_n300<- write.csv(Phi_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8//Phi_sim3_n300.csv")
overdisp_sim3_n300<- write.csv(overdisp_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim3_n300.csv")
size_sim3_n300<- write.csv(size_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim3_n300.csv")
MU1_sim3_n300<- write.csv(MSE_mu1,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim3_n300.csv")
MU2_sim3_n300<- write.csv(MSE_mu2,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim3_n300.csv")
V_M_sim3_n600<- write.csv(V_M,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim3_n300.csv")
elapsed_sim3_n300<- write.csv(elapsed,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim3_n300.csv")


```




``` {r Scenario1-sim4,eval=TRUE,echo=FALSE}
rm(list = ls())
source("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Cases/ZINB_March2023.R")

###################################################################################################

###################################################################################################
###################################################################################################
### Data sim_3###
### Generate Y Matrix_Matrix of raw counts###
### case_1###
set.seed(444)
N<- 600
G<- 120
P<- c(0.5,0.5)
Phi<- c(0.1,0.1)
K<- length(P)
#size<- c(10,5)
#size<- c(5,10)
size<- c(5,20)

#P<- c(0.25,0.25,0.25,0.25)
#N<- 1000
#G<- 10
#Phi<- c(0.1,0.1,0.2,0.2)
#P<- c(0.25,0.25,0.25,0.25)
#P1<- c(0.4,0.3,0.2,0.1)


#mu_1<- rgamma(n=G,shape=10,scale=1/2)
#mu_2<- rgamma(n=G,shape=10,scale=1/1.5)


#mu_1<- c(rep(5,(G/2)),rep(10,G/2))
#mu_2<- c(rep(10,(G/2)),rep(5,G/2))

mu_1<- c(rep(5,G))
mu_2<- c(rep(10,G))

MU<- rbind(mu_1,mu_2)
#MU

#S<- 256
#S<- 128
S<- 100
#S<- 3
P_hat<- matrix(NA,ncol=length(P),nrow=S)
#P_hat<- NULL
Phi_hat<- matrix(NA,ncol=length(P),nrow=S)
overdisp_hat<- matrix(NA,nrow=S,ncol=K)
size_hat<- matrix(NA,nrow=S,ncol=K)

#Phi_hat
#phi_hat2<- NULL
mu1_hat<- matrix(NA,ncol = G,nrow=S)
mu2_hat<- matrix(NA,ncol = G,nrow=S)
#lambda3_hat<- matrix(NA,ncol = G,nrow=S)
#lambda4_hat<- matrix(NA,ncol = G,nrow=S)

#MU_1<- MU_2<- matrix(NA,nrow=S,ncol=G)
V_M<- rep(NA,S)
elapsed<- rep(NA,S)

for(s in 1:S){

  # mu_1<- rgamma(n=G,shape=10,scale=1/2)


  #mu_2<- rgamma(n=G,shape=10,scale=1/0.2)

  #MU<- rbind(mu_1,mu_2)



  #for(s in 1:S){


  #for(iteration in 1:r){

  #p_hat<- NULL
  #phi_hat1<- NULL
  #phi_hat2<- NULL
  #lambda1_hat<- matrix(0,ncol = G,nrow=r)
  #lambda2_hat<- matrix(0,ncol = G,nrow=r)

  #for(iter in 1:r){
  #clust<- rbinom(size=1,n=N,p=0.5)
  clust<- sample(1:2,size=N,replace = TRUE,prob=P)
  #clust
  #length(clust[clust==1])


  #clust<- sample(c(1,2),size=N,replace = TRUE,prob=pn)
  #clust


  cell_matrix<- U_ng<-  matrix(rep(0,N*G),nrow=N,ncol=G)

  for(n in 1:N){
    for(g in 1:G){
      if(clust[n]==1) {
        out_1 = ZINB_r_U(n=1,prob=Phi[1],theta=MU[1,g],disp_param=size[1])
        cell_matrix[n,g]<- out_1$Y
        U_ng[n,g]<- out_1$U}

      else if(clust[n]==2){
        out_2 = ZINB_r_U(n=1,prob=Phi[2],theta=MU[2,g],disp_param=size[2])
        cell_matrix[n,g]<- out_2$Y
        U_ng[n,g]<- out_2$U}

    }
  }





#cell_matrix
  #cell_matrix

  #plot(hclust(dist(cell_matrix)))


  #cell_matrix
  #dim(cell_matrix)


  #result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)
  elapsed[s]<- system.time({result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)})["elapsed"]
  P_hat[s,]<- result_test$P
  Phi_hat[s,]<- result_test$Phi
  mu1_hat[s,]<- result_test$MU[1,]
  mu2_hat[s,]<- result_test$MU[2,]
  overdisp_hat[s,]<- result_test$a_hat
  size_hat[s,]<- result_test$size_est
   Z0<- clust
   zhat<- result_test$postprobs
   zhat<- apply(zhat,1,which.max)
   V_M[s]<- v_measure(Z0,zhat)



}




###############################################################
L1<- cbind(colMeans(mu1_hat),mu_1)
colnames(L1)<- c("mu1_hat","mu1")
#print(L1)
L2<- cbind(colMeans(mu2_hat),mu_2)
colnames(L2)<- c("mu2_hat","mu2")
#print(L2)

dif_mu1<- dif_mu2<- matrix(NA,nrow=S,ncol=G)

for(s in 1:S){
  dif_mu1[s,]<- (mu1_hat[s,]-mu_1)^2
  dif_mu2[s,]<- (mu2_hat[s,]-mu_2)^2

}

#dif_mu1
#dif_mu2

MSE_mu1<- apply(dif_mu1,2,mean)
#MSE_mu1
#mean(MSE_mu1)

MSE_mu2<- apply(dif_mu2,2,mean)
#MSE_mu2
#mean(MSE_mu2)
#mu1_hat
#boxplot(mu1_hat)
#abline(h=5)
#abline(h=10)

#boxplot(mu2_hat)
#abline(h=5)
#abline(h=10)

#MSE_mu1
#MSE_mu2
MSE_MU<- rbind(mean(MSE_mu1),mean(MSE_mu2))
#MSE_MU
#xtable(MSE_MU)
#mean(MSE_mu1)

#########################################################################################

P_sim4_n600<- write.csv(P_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim4_n600.csv")
Phi_sim4_n600<- write.csv(Phi_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8//Phi_sim4_n600.csv")
overdisp_sim4_n600<- write.csv(overdisp_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim4_n600.csv")
size_sim4_n600<- write.csv(size_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim4_n600.csv")
MU1_sim4_n600<- write.csv(MSE_mu1,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim4_n600.csv")
MU2_sim4_n600<- write.csv(MSE_mu2,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim4_n600.csv")
V_M_sim4_n600<- write.csv(V_M,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim4_n600.csv")
elapsed_sim4_n600<- write.csv(elapsed,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim4_n600.csv")


```



``` {r Scenario1-sim5,eval=TRUE,echo=FALSE}
rm(list = ls())
source("E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Cases/ZINB_March2023.R")

###################################################################################################

###################################################################################################
###################################################################################################
### Data sim_4###
### Generate Y Matrix_Matrix of raw counts###
### case_1###
set.seed(555)

N<- 1200
G<- 120
P<- c(0.5,0.5)
Phi<- c(0.1,0.1)
K<- length(P)
#size<- c(10,5)
#size<- c(5,10)
size<- c(5,20)

#P<- c(0.25,0.25,0.25,0.25)
#N<- 1000
#G<- 10
#Phi<- c(0.1,0.1,0.2,0.2)
#P<- c(0.25,0.25,0.25,0.25)
#P1<- c(0.4,0.3,0.2,0.1)


#mu_1<- rgamma(n=G,shape=10,scale=1/2)
#mu_2<- rgamma(n=G,shape=10,scale=1/1.5)


#mu_1<- c(rep(5,(G/2)),rep(10,G/2))
#mu_2<- c(rep(10,(G/2)),rep(5,G/2))

mu_1<- c(rep(5,G))
mu_2<- c(rep(10,G))
MU<- rbind(mu_1,mu_2)
#MU

#S<- 256
#S<- 128
S<- 100
#S<- 3
P_hat<- matrix(NA,ncol=length(P),nrow=S)
#P_hat<- NULL
Phi_hat<- matrix(NA,ncol=length(P),nrow=S)
overdisp_hat<- matrix(NA,nrow=S,ncol=K)
size_hat<- matrix(NA,nrow=S,ncol=K)

#Phi_hat
#phi_hat2<- NULL
mu1_hat<- matrix(NA,ncol = G,nrow=S)
mu2_hat<- matrix(NA,ncol = G,nrow=S)
#lambda3_hat<- matrix(NA,ncol = G,nrow=S)
#lambda4_hat<- matrix(NA,ncol = G,nrow=S)

#MU_1<- MU_2<- matrix(NA,nrow=S,ncol=G)
V_M<- rep(NA,S)
elapsed<- rep(NA,S)

for(s in 1:S){

  # mu_1<- rgamma(n=G,shape=10,scale=1/2)


  #mu_2<- rgamma(n=G,shape=10,scale=1/0.2)

  #MU<- rbind(mu_1,mu_2)



  #for(s in 1:S){


  #for(iteration in 1:r){

  #p_hat<- NULL
  #phi_hat1<- NULL
  #phi_hat2<- NULL
  #lambda1_hat<- matrix(0,ncol = G,nrow=r)
  #lambda2_hat<- matrix(0,ncol = G,nrow=r)

  #for(iter in 1:r){
  #clust<- rbinom(size=1,n=N,p=0.5)
  clust<- sample(1:2,size=N,replace = TRUE,prob=P)
  #clust
  #length(clust[clust==1])


  #clust<- sample(c(1,2),size=N,replace = TRUE,prob=pn)
  #clust


  cell_matrix<- U_ng<-  matrix(rep(0,N*G),nrow=N,ncol=G)

  for(n in 1:N){
    for(g in 1:G){
      if(clust[n]==1) {
        out_1 = ZINB_r_U(n=1,prob=Phi[1],theta=MU[1,g],disp_param=size[1])
        cell_matrix[n,g]<- out_1$Y
        U_ng[n,g]<- out_1$U}

      else if(clust[n]==2){
        out_2 = ZINB_r_U(n=1,prob=Phi[2],theta=MU[2,g],disp_param=size[2])
        cell_matrix[n,g]<- out_2$Y
        U_ng[n,g]<- out_2$U}

    }
  }








#cell_matrix
  #cell_matrix

  #plot(hclust(dist(cell_matrix)))


  #cell_matrix
  #dim(cell_matrix)


  #result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)
  elapsed[s]<- system.time({result_test<- ZINB_mix_K_comp(Y=cell_matrix,P=P,Phi=Phi,mu=MU,dispresiopn_parameter=size,eps=1e-5, maxit=1000)})["elapsed"]
  P_hat[s,]<- result_test$P
  Phi_hat[s,]<- result_test$Phi
  mu1_hat[s,]<- result_test$MU[1,]
  mu2_hat[s,]<- result_test$MU[2,]
  overdisp_hat[s,]<- result_test$a_hat
  size_hat[s,]<- result_test$size_est
   Z0<- clust
   zhat<- result_test$postprobs
   zhat<- apply(zhat,1,which.max)
   V_M[s]<- v_measure(Z0,zhat)



}




###############################################################
L1<- cbind(colMeans(mu1_hat),mu_1)
colnames(L1)<- c("mu1_hat","mu1")
#print(L1)
L2<- cbind(colMeans(mu2_hat),mu_2)
colnames(L2)<- c("mu2_hat","mu2")
#print(L2)

dif_mu1<- dif_mu2<- matrix(NA,nrow=S,ncol=G)

for(s in 1:S){
  dif_mu1[s,]<- (mu1_hat[s,]-mu_1)^2
  dif_mu2[s,]<- (mu2_hat[s,]-mu_2)^2

}

#dif_mu1
#dif_mu2

MSE_mu1<- apply(dif_mu1,2,mean)
#MSE_mu1
#mean(MSE_mu1)

MSE_mu2<- apply(dif_mu2,2,mean)
#MSE_mu2
#mean(MSE_mu2)
#mu1_hat
#boxplot(mu1_hat)
#abline(h=5)
#abline(h=10)

#boxplot(mu2_hat)
#abline(h=5)
#abline(h=10)

#MSE_mu1
#MSE_mu2
MSE_MU<- rbind(mean(MSE_mu1),mean(MSE_mu2))
#MSE_MU
#xtable(MSE_MU)
#mean(MSE_mu1)

#########################################################################################

P_sim5_n1200<- write.csv(P_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/P_sim5_n1200.csv")
Phi_sim5_n1200<- write.csv(Phi_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/Phi_sim5_n1200.csv")
overdisp_sim5_n1200<- write.csv(overdisp_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/overdisp_sim5_n1200.csv")
size_sim5_n1200<- write.csv(size_hat,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/size_sim5_n1200.csv")
MU1_sim5_n1200<- write.csv(MSE_mu1,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU1_sim5_n1200.csv")
MU2_sim5_n1200<- write.csv(MSE_mu2,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/MU2_sim5_n1200.csv")
V_M_sim5_n1200<- write.csv(V_M,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/v_M_sim5_n1200.csv")
elapsed_sim5_n1200<- write.csv(elapsed,"E:/Thesis-Feb,March2022/Programming Project 2/ZINB_A/Scenario8/elapsed_sim5_n1200.csv")


```


